### DISCUSSION TITLE
cache not working as expected

### DISCUSSION THREAD

**Discussion by Saifallak** [subosito/flutter-action#141] [General]
cache key is wrong i guess ?

![image](https://user-images.githubusercontent.com/6053156/155222719-ba18fa18-949f-48e7-8423-8043581df3ed.png)

![image](https://user-images.githubusercontent.com/6053156/155223434-1969dd0c-733d-47e7-89bc-ac1971060314.png)

here is my main.yml

```yml
# This is a basic workflow to help you get started with Actions

name: FlutterBuild

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags:
      - "*.*.*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
        cache: 'gradle'
        check-latest: true
    - name: Setup Flutter & Build APK/AAB
      uses: subosito/flutter-action@v2
      with:
        channel: 'beta'
        cache: true
        cache-key: flutter # optional, change this to force refresh cache
        cache-path: ${{ runner.tool_cache }}/flutter # optional, change this to specify the cache path
    - run: flutter --version
    - run: flutter pub upgrade
    - run: flutter build apk
    - run: flutter build appbundle
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab

```
