### DISCUSSION TITLE
flutter config --enable-linux-desktop doesn't apply before building

### DISCUSSION THREAD

**Discussion by mpconte** [subosito/flutter-action#142] [General]
With the sample workflow:

```
name: Build Flutter Demo for Linux

on:
  workflow_dispatch:  
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2      
     
      - uses: subosito/flutter-action@v2
        with:
         channel: 'stable'

      - run: |
          sudo apt-get update -y
          sudo sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev 
      
      - name: Enable Linux desktop development 
        run: |          
          flutter config --enable-linux-desktop
                
      - name: Build linux application
        run: |
          flutter packages get
          flutter build linux
```

Returns the following error on **flutter build linux**:

![image](https://user-images.githubusercontent.com/7958011/154339819-8c96ebe8-9647-4879-bca7-95c78d3aaa14.png)
