### DISCUSSION TITLE
Error when running it: /Users/runner/work/_actions/subosito/flutter-action/v2/setup.sh: line 59: /Users/runner/work/_temp/: Is a directory

### DISCUSSION THREAD

**Discussion by fzyzcjy** [subosito/flutter-action#173] [General]
See here for full github action run: https://github.com/fzyzcjy/flutter_rust_bridge/runs/6871188630?check_suite_focus=true

```
Run subosito/flutter-action@v2
  with:
    channel: stable
    architecture: x64
    flutter-version: any
    cache-key: flutter
    cache-path: /Users/runner/hostedtoolcache/flutter
  env:
    CARGO_TERM_COLOR: always
Run $GITHUB_ACTION_PATH/setup.sh -c "/Users/runner/hostedtoolcache/flutter" stable any x64
  $GITHUB_ACTION_PATH/setup.sh -c "/Users/runner/hostedtoolcache/flutter" stable any x64
  shell: /bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    CARGO_TERM_COLOR: always
usage: basename string [suffix]
       basename [-a] [-s suffix] string [...]
/Users/runner/work/_actions/subosito/flutter-action/v[2](https://github.com/fzyzcjy/flutter_rust_bridge/runs/6871188630?check_suite_focus=true#step:4:2)/setup.sh: line [5](https://github.com/fzyzcjy/flutter_rust_bridge/runs/6871188630?check_suite_focus=true#step:4:5)[9](https://github.com/fzyzcjy/flutter_rust_bridge/runs/6871188630?check_suite_focus=true#step:4:9): /Users/runner/work/_temp/: Is a directory
tar: Error opening archive: Error reading '/Users/runner/work/_temp/'
rm: /Users/runner/work/_temp/: is a directory
```

```
Current runner version: '2.292.0'
Operating System
  macOS
  11.6.6
  [2](https://github.com/fzyzcjy/flutter_rust_bridge/runs/6871188630?check_suite_focus=true#step:1:2)0G624
Virtual Environment
  Environment: macos-11
  Version: 20220605.1
  Included Software: https://github.com/actions/virtual-environments/blob/macOS-11/20220605.1/images/macos/macos-11-Readme.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/macOS-11%2F20220605.1
Virtual Environment Provisioner
  1.0.0.0-main-202205[3](https://github.com/fzyzcjy/flutter_rust_bridge/runs/6871188630?check_suite_focus=true#step:1:3)1-1
GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'subosito/flutter-action@v2' (SHA:d8687e6979e8ef66d2b2970e2c92c1d8e801d7bf)
Download action repository 'actions/checkout@v2' (SHA:788[4](https://github.com/fzyzcjy/flutter_rust_bridge/runs/6871188630?check_suite_focus=true#step:1:4)fcad6b[5](https://github.com/fzyzcjy/flutter_rust_bridge/runs/6871188630?check_suite_focus=true#step:1:5)d53d10323aee724dc[6](https://github.com/fzyzcjy/flutter_rust_bridge/runs/6871188630?check_suite_focus=true#step:1:7)8d8b9096a2e)
Download action repository 'actions-rs/toolchain@v1' (SHA:16499b5e05bf2e268[7](https://github.com/fzyzcjy/flutter_rust_bridge/runs/6871188630?check_suite_focus=true#step:1:8)9000db0c1d13f7e13fa3af)
Getting action download info
Download action repository 'actions/cache@v2' (SHA:937d244753[8](https://github.com/fzyzcjy/flutter_rust_bridge/runs/6871188630?check_suite_focus=true#step:1:9)1cd[9](https://github.com/fzyzcjy/flutter_rust_bridge/runs/6871188630?check_suite_focus=true#step:1:10)c75ae6db[12](https://github.com/fzyzcjy/flutter_rust_bridge/runs/6871188630?check_suite_focus=true#step:1:14)cb4e79714b926ed)
```
