### DISCUSSION TITLE
Unable to determine Flutter version for channel: stable version: x64 architecture:

### DISCUSSION THREAD

**Discussion by carloshenrique-dev** [subosito/flutter-action#206] [General]
I get this issue today, how can I fix it? I did not change the workflow recently.

![image](https://user-images.githubusercontent.com/58753717/221274072-4ba56fbf-146b-4d1b-8893-fe8b3c90c358.png)

**Comment by joseph-grabinger** [comment]
Same here! `Unable to determine Flutter version for channel: master version: any architecture: x64`
The action worked fine yesterday.

Here is my workflow:
```yml
name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Clone Flutter repository with master channel
        uses: subosito/flutter-action@v2
        with:
          channel: master
      - run: flutter doctor -v
      - run: flutter pub get
```

This is my error: 
```
Run subosito/flutter-action@v2
  with:
    channel: master
    flutter-version: any
    cache: false
    cache-key: flutter-:os:-:channel:-:version:-:arch:-:hash:
    cache-path: /opt/hostedtoolcache/flutter/:channel:-:version:-:arch:
    architecture: X64
Run $GITHUB_ACTION_PATH/setup.sh -p -c '/opt/hostedtoolcache/flutter/:channel:-:version:-:arch:' -k 'flutter-:os:-:channel:-:version:-:arch:-:hash:' -n 'any' -a 'X64' master
  $GITHUB_ACTION_PATH/setup.sh -p -c '/opt/hostedtoolcache/flutter/:channel:-:version:-:arch:' -k 'flutter-:os:-:channel:-:version:-:arch:-:hash:' -n 'any' -a 'X64' master
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
Unable to determine Flutter version for channel: master version: any architecture: x64
Error: Process completed with exit code 1.
```
