### DISCUSSION TITLE
flutter pub get issue with github

### DISCUSSION THREAD

**Discussion by bmd007** [subosito/flutter-action#216] [General]
Hi
I have a package which should be downloaded from a github repo like:
```
  rsocket:
    git:
      url: git@github.com:rsocket/rsocket-dart.git
      ref: master
```
When I can locally run `flutter pub get` all is fine.
However, 
```
      - name: flutter pub get
        run: flutter pub get
```
fails with 
```
Running "flutter pub get" in dance_partner_finder...            
Git error. Command: `git clone --mirror git@github.com:rsocket/rsocket-dart.git /opt/hostedtoolcache/flutter/stable-3.3.10-x64/.pub-cache/git/cache/rsocket-dart-09a70c15[8]
stderr: Cloning into bare repository '/opt/hostedtoolcache/flutter/stable-3.3.[10](https://github.com/bmd007/wonderland/actions/runs/3797083664/jobs/6457732719#step:6:11)-x64/.pub-cache/git/cache/rsocket-dart-09a70c158fe137d63f8e0090b93431e1d730b21d'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
.

The mentioned repo is public and doesn't need access permission.
How can I resolve this?

Thanks in advance

**Comment by bmd007** [comment]
complete GitHub action file in case it helps:
https://github.com/bmd007/wonderland/blob/master/.github/workflows/main.yml

an example run:
https://github.com/bmd007/wonderland/actions/runs/3797083664/jobs/6457732719

**Comment by AsturaPhoenix** [comment]
It looks like using an ssh git url in the pubspec may always require an ssh key, even for public repos. Changing the url to https seems to work:

```
  rsocket:
    git:
      url: https://github.com/rsocket/rsocket-dart.git
      ref: master
```
