### DISCUSSION TITLE
Is there dart 3 update?

### DISCUSSION THREAD

**Discussion by Add00w** [subosito/flutter-action#235] [General]
The current Dart SDK version is 2.19.0.

Because .... requires SDK version >=3.0.0 <4.0.0, version solving failed.

**Comment by Add00w** [comment]
@subosito

**Comment by rk0cc** [comment]
I got no problem with same SDK constraint which applied `channel: stable` in `with` section.

It may be better if you can provide few lines in your action's configuration to investigate the problem.

**Comment by Add00w** [comment]
> I got no problem with same SDK constraint which applied `channel: stable` in `with` section.
> 
> It may be better if you can provide few lines in your action's configuration to investigate the problem.

```
name: Analyze and test the source code
on:
  pull_request:
    branches:
      - develop
jobs:
  test:
    name: Analyze the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
          channel: 'stable'
      - name: Install packages
        run: flutter pub get
      - name: Generate localizations
        run:  flutter gen-l10n
      - name: Generate configs
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Linter
        run: flutter analyze
      - name: Test the code
        run: flutter test
```

Here is sample

**Comment by HannesGitH** [comment]
~~another parameter `sdk-version` would also be super nice, so we can use this action like:~~
<details>
<summary>workflow snippet</summary>

```yaml
- uses: subosito/flutter-action@v2
   with:
     flutter-version: '3.10.0'
     channel: 'stable'
     sdk-version: '3.0.1'
```

</details>
