### DISCUSSION TITLE
can not use the specific version

### DISCUSSION THREAD

**Discussion by Copperfiled** [subosito/flutter-action#252] [General]
- uses: subosito/flutter-action@v2
  with:
    flutter-version: '3.7.9'
    channel: 'stable'
- run: flutter --version

I got 3.10.2 which is the lastest version, not the specific version.

**Comment by pjung-bosch** [comment]
I have the same problem; after this step
```
- name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.2'
          channel: 'stable'
          cache: false
```

I get 
``` 
Flutter 3.10.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9cd3d0d9ff (9 days ago) • 2023-05-23 20:57:28 -0700
Engine • revision 90fa3ae28f
Tools • Dart 3.0.2 • DevTools 2.23.1
```

It used to work fine until recently.

**Comment by vakaszia** [comment]
Yes I'm having the same issue. It's not working with specific version.

**Comment by dokkaebi** [comment]
I ran into a similar issue when I updated from 3.10.x to 3.13.0, but it was a cache problem. The new version was downloaded, but then the old version was used. I updated my cache key to include the flutter version (previously, I just had `cache-key: flutter`), and now it works.

```
- uses: subosito/flutter-action@v2
  with:
    cache: true
    cache-key: flutter-${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
    cache-path: ${{ runner.tool_cache }}/flutter
    architecture: x64
    flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
```
