### DISCUSSION TITLE
v2.15.0

### DISCUSSION THREAD

**Discussion by bartekpacia** [subosito/flutter-action#293] [General]
Hi! I'm Bartek and I'm a new maintainer of this action. I promise to take good care of it.

This release introduces the `flutter-version-file` option, which lets you easily centralize Flutter version in a single place – your pubspec.yaml file:

You can use it like this:

```yaml
steps:
  - name: Clone repository
    uses: actions/checkout@v4
  - name: Set up Flutter
    uses: subosito/flutter-action@v2
    with:
      channel: stable
      flutter-version-file: pubspec.yaml # path to pubspec.yaml
```

Please note that for this to work, you need to specify exact Flutter version in pubspec.yaml:

```yaml
environment:
  dart: ">=3.3.0 <4.0.0"
  flutter: 3.19.0 # This must be exact! No ranges allowed.
```

Apart from that, some minor README updates and code cleanup was performed.

<hr /><em>This discussion was created from the release <a href='https://github.com/subosito/flutter-action/releases/tag/v2.15.0'>v2.15.0</a>.</em>
