### DISCUSSION TITLE
Setting Flutter environment based on FVM

### DISCUSSION THREAD

**Discussion by Gj1337** [subosito/flutter-action#356] [Ideas]
[FVM](https://fvm.app/) is a quite popular tool for managing Flutter SDK. A lot of projects use FVM and it would be a great to have opportunity establish Flutter based on FVM config. 

Something like
```yaml
steps:
  - name: Clone repository
    uses: actions/checkout@v4
  - name: Set up Flutter
    uses: subosito/flutter-action@v2
    with:
      use_fvm: true
  - run: fvm flutter --versios
  ```
