### ISSUE TITLE
Support reading Flutter version from config file (FVM)

### ISSUE THREAD

**Issue by kuhnroyal** [subosito/flutter-action#101]
I want to bring this up for consideration. FVM (https://github.com/leoafarias/fvm) is a pretty popular version manager for Flutter. It would be great if the action would support reading the Flutter version/channel from its config file in `.fvm/fvm_config.json` similar to the ruby action and others.

Currently I am reading the version manually from the JSON file in every pipeline:
```yaml
      - name: Determine Flutter version
        uses: antifree/json-to-variables@v1.0.1
        with:
          filename: '.fvm/fvm_config.json'
          prefix: fvm
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.fvm_flutterSdkVersion }}
```

This could just be something like this:
```yaml
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '.fvm/fvm_config.json'
```

I would love to create a PR if there is interest for this.

**Comment by kuhnroyal** [comment]
I created a simple action that parses the FVM config file. It can be used together with flutter-action as well as with custom setup.

https://github.com/kuhnroyal/flutter-fvm-config-action

**Comment by RafaRuiz** [comment]
Why an extra action has to take place when this is enough.
Take a look at [`actions/setup-node@v4`](https://github.com/actions/setup-node):

```
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
```

that's enough.
