### ISSUE TITLE
Downloading artifacts 

### ISSUE THREAD

**Issue by proismailshah** [subosito/flutter-action#102]
How can I download artifacts with this workflow

**Comment by rares45** [comment]
You can add a step to upload the artfacts:

- android:
```
- name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: android
        path: build/app/outputs/flutter-apk/app-release.apk
```
- linux:
```
- name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: linux_64
        path: build/linux/x64/release/bundle/
```
- windows:
```
- name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: windows_64
          path: build/windows/runner/Release/
```
