### ISSUE TITLE
building too slow on mac 

### ISSUE THREAD

**Issue by jianboy** [subosito/flutter-action#110]
This action costs 6 minute.
![image](https://user-images.githubusercontent.com/11532015/127050337-001fa126-e5d2-4c33-bf54-9f8baf275436.png)

setting:

```
      - name: Flutter action
        uses: subosito/flutter-action@v1.5.3
        with:
          channel: "stable"
          flutter-version: "2.0.5"
```

**Comment by Nealsoni00** [comment]
same -- any progress on this?

**Comment by Nealsoni00** [comment]
Adding this brings the action down to 0 seconds on MacOS
```
# different on macos vs linux https://github.com/subosito/flutter-action/issues/16#issuecomment-574300350
      - name: Get Cached Flutter Dependencies
        uses: actions/cache@v2
        with:
          path: /Users/runner/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-2.2.3

```
