### ISSUE TITLE
Unable to find release for 2.5 

### ISSUE THREAD

**Issue by apomalyn** [subosito/flutter-action#115]
Hi! 
Since the release of 2.5 the flutter stay stuck at 2.2.1 even if I force the version like this:

```yaml
- uses: subosito/flutter-action@v1.5.0
   with:
      flutter-version: '2.5.x' # or 2.5
      channel: 'stable'
```

<img width="341" alt="Screen Shot 2021-09-22 at 7 58 34 PM" src="https://user-images.githubusercontent.com/22211097/134437241-0321f6d3-1b4c-46ef-8bb2-e2556a5145e3.png">

Do you have an idea of what is the problem?
