### ISSUE TITLE
jq: command not found

### ISSUE THREAD

**Issue by ArneSaknussemm89** [subosito/flutter-action#131]
Just started configuring this on a personal project. Here's my `action.yml` file:
```
name: Dart CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image:  dart:stable
    
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter packages get
    - run: flutter test --coverage="coverage"
    - run: flutter pub run coverage:format_coverage --lcov --in=coverage --out=coverage.lcov --packages=.packages --report-on=lib
    - name: Upload coverage to Codecov  
      uses: codecov/codecov-action@v2
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: coverage.lcov
```

And this is the error that is thrown:
```
Run subosito/flutter-action@v[2](https://github.com/ArneSaknussemm89/styx/runs/5058744223?check_suite_focus=true#step:4:2)
  with:
    channel: stable
    cache-key: flutter
    cache-path: /opt/hostedtoolcache/flutter
Run $GITHUB_ACTION_PATH/setup.sh -c "/opt/hostedtoolcache/flutter" stable 
  $GITHUB_ACTION_PATH/setup.sh -c "/opt/hostedtoolcache/flutter" stable 
  shell: bash --noprofile --norc -e -o pipefail {0}
/__w/_actions/subosito/flutter-action/v2/setup.sh: line 17: jq: command not found
/__w/_actions/subosito/flutter-action/v2/setup.sh: line 106: jq: command not found
basename: missing operand
Try 'basename --help' for more information.
/__w/_actions/subosito/flutter-action/v2/setup.sh: line 5[3](https://github.com/ArneSaknussemm89/styx/runs/5058744223?check_suite_focus=true#step:4:3): /github/home/: Is a directory
tar: /github/home/: Cannot read: Is a directory
tar: At beginning of tape, quitting now
tar: Error is not recoverable: exiting now
rm: cannot remove '/github/home/': Is a directory
```

Am I missing something? I followed a couple tutorials but it's possible it's changed since those.
