### ISSUE TITLE
unable to invoke app via flutter drive

### ISSUE THREAD

**Issue by Bhupesh-V** [subosito/flutter-action#135]
A bunch of weird errors are raised when trying to run integration tests.

Aciton config

```yaml
name: Integration Tests
on:
  push:
  workflow_dispatch:

jobs:
  integration_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        filename: ["my_file.dart"]
    name: "Android"
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.2.3'
          channel: 'stable'
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter
      - run: flutter doctor -v
      - name: "${{ matrix.filename }}"
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 27
          target: default
          arch: x86_64
          profile: Nexus 6
          script: "flutter drive --profile --flavor staging --driver=test_driver/integration_driver.dart --target=integration_test/${{ matrix.filename }} --android-emulator"
```

<details>
<summary>Action Error Log</summary>
<code>
../../../.pub-cache/hosted/pub.dartlang.org/google_fonts-2.3.0/lib/google_fonts.dart:2881:7: Error: No named parameter with the name 'displayLarge'.
      displayLarge: GoogleFonts.aBeeZee(textStyle: textTheme.displayLarge),
      ^^^^^^^^^^^^
/opt/hostedtoolcache/flutter/packages/flutter/lib/src/material/text_theme.dart:113:9: Context: Found this candidate, but the arguments don't match.
  const TextTheme({
        ^^^^^^^^^
../../../.pub-cache/hosted/pub.dartlang.org/google_fonts-2.3.0/lib/google_fonts.dart:2968:7: Error: No named parameter with the name 'displayLarge'.
      displayLarge: GoogleFonts.abel(textStyle: textTheme.displayLarge),
      ^^^^^^^^^^^^
/opt/hostedtoolcache/flutter/packages/flutter/lib/src/material/text_theme.dart:113:9: Context: Found this candidate, but the arguments don't match.
  const TextTheme({
        ^^^^^^^^^
../../../.pub-cache/hosted/pub.dartlang.org/google_fonts-2.3.0/lib/google_fonts.dart:3083:7: Error: No named parameter with the name 'displayLarge'.
      displayLarge: GoogleFonts.abhayaLibre(textStyle: textTheme.displayLarge),
      ^^^^^^^^^^^^
/opt/hostedtoolcache/flutter/packages/flutter/lib/src/material/text_theme.dart:113:9: Context: Found this candidate, but the arguments don't match.
  const TextTheme({
        ^^^^^^^^^
../../../.pub-cache/hosted/pub.dartlang.org/google_fonts-2.3.0/lib/google_fonts.dart:3174:7: Error: No named parameter with the name 'displayLarge'.
      displayLarge: GoogleFonts.abrilFatface(textStyle: textTheme.displayLarge),
      ^^^^^^^^^^^^
/opt/hostedtoolcache/flutter/packages/flutter/lib/src/material/text_theme.dart:113:9: Context: Found this candidate, but the arguments don't match.
  const TextTheme({
        ^^^^^^^^^

../../../.pub-cache/hosted/pub.dartlang.org/google_fonts-2.3.0/lib/google_fonts.dart:3265:7: Error: No named parameter with the name 'displayLarge'.
      displayLarge: GoogleFonts.aclonica(textStyle: textTheme.displayLarge),
      ^^^^^^^^^^^^
/opt/hostedtoolcache/flutter/packages/flutter/lib/src/material/text_theme.dart:113:9: Context: Found this candidate, but the arguments don't match.
  const TextTheme({
        ^^^^^^^^^
../../../.pub-cache/hosted/pub.dartlang.org/google_fonts-2.3.0/lib/google_fonts.dart:[335](https://github.com/CreatorStack/creatorstack_mobile/runs/5094800383?check_suite_focus=true#step:5:335)2:7: Error: No named parameter with the name 'displayLarge'.
      displayLarge: GoogleFonts.acme(textStyle: textTheme.displayLarge),
      ^^^^^^^^^^^^
/opt/hostedtoolcache/flutter/packages/flutter/lib/src/material/text_theme.dart:113:9: Context: Found this candidate, but the arguments don't match.
  const TextTheme({
        ^^^^^^^^^
../../../.pub-cache/hosted/pub.dartlang.org/google_fonts-2.3.0/lib/google_fonts.dart:[343](https://github.com/CreatorStack/creatorstack_mobile/runs/5094800383?check_suite_focus=true#step:5:343)9:7: Error: No named parameter with the name 'displayLarge'.
      displayLarge: GoogleFonts.actor(textStyle: textTheme.displayLarge),
      ^^^^^^^^^^^^
/opt/hostedtoolcache/flutter/packages/flutter/lib/src/material/text_theme.dart:113:9: Context: Found this candidate, but the arguments don't match.
  const TextTheme({

....
</code>
</details>

`flutter doctor -v`
```bash
Running "flutter pub get" in flutter_tools...                       6.9s
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale C.UTF-8)
    • Flutter version 2.2.3 at /opt/hostedtoolcache/flutter
    • Framework revision f4abaa0735 (7 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 2[41](https://github.com/CreatorStack/creatorstack_mobile/runs/5094800383?check_suite_focus=true#step:4:41)c87ad80
    • Dart version 2.13.4
[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /usr/local/lib/android/sdk
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = /usr/local/lib/android/sdk
    • ANDROID_SDK_ROOT = /usr/local/lib/android/sdk
    • Java binary at: /usr/lib/jvm/temurin-11-jdk-amd64/bin/java
    • Java version OpenJDK Runtime Environment Temurin-11.0.13+8 (build 11.0.13+8)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Chrome - develop for the web
    • Chrome at google-chrome
[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 97.0.[46](https://github.com/CreatorStack/creatorstack_mobile/runs/5094800383?check_suite_focus=true#step:4:46)92.99
! Doctor found issues in 2 categories.
```
