### ISSUE TITLE
flutter config --enable-linux-desktop doesn't apply before building

### ISSUE THREAD

**Issue by mpconte** [subosito/flutter-action#139]
With the sample workflow:

```
name: Build Flutter Demo for Linux

on:
  workflow_dispatch:  
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2      
     
      - uses: subosito/flutter-action@v2
        with:
         channel: 'stable'

      - run: |
          sudo apt-get update -y
          sudo sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev 
      
      - name: Enable Linux desktop development 
        run: |          
          flutter config --enable-linux-desktop
                
      - name: Build linux application
        run: |
          flutter packages get
          flutter build linux
```

Returns the following error:

Run flutter packages get
  flutter packages get
  flutter build linux
  shell: /usr/bin/bash -e {0}
  env:
    FLUTTER_ROOT: /opt/hostedtoolcache/flutter
    PUB_CACHE: /home/runner/.pub-cache
Running "flutter pub get" in flutter_tools...                       9.6s
Running "flutter pub get" in flutter_demo...                        8.[4](https://github.com/SensoftInc/flutter_demo/runs/5221745666?check_suite_focus=true#step:6:4)s

💪 Building with sound null safety 💪

No Linux desktop project configured. See https://docs.flutter.dev/desktop#add-desktop-support-to-an-existing-flutter-app to learn about adding Linux support to a project.
Error: Process completed with exit code 1.
