### ISSUE TITLE
Location of `.pub-cache`

### ISSUE THREAD

**Issue by marvin-kolja** [subosito/flutter-action#143]
First of all, thanks for this awesome Github action!

I tried to get pub package caching working and stumbled upon a related [issue](https://github.com/subosito/flutter-action/issues/16) which discusses the caching, too. Currently the `PUB_CACHE` variable is set to the `$HOME` dir (or in case of windows `$USERPROFILE`). Is there any specific reason for that?

Right now I have to reassign `PUB_CACHE` in order to have a "cacheable" dir:

```yaml
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.8.1'
          channel: 'stable'
          cache: true

      - run: echo "PUB_CACHE=${{ runner.tool_cache }}/.pub-cache" >> $GITHUB_ENV
      - run: echo "${PUB_CACHE}/bin" >> $GITHUB_PATH

      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: ${{ env.PUB_CACHE }}
          key: deps-${{ hashFiles('**/pubspec.lock') }}

      - run: flutter pub get
```

It would be nice to change `PUB_CACHE` to a more default directory or allow to set a custom dir.

Thanks in advance!
