### ISSUE TITLE
Empty directory for ios build using macos

### ISSUE THREAD

**Issue by Andrflor** [subosito/flutter-action#157]
I have been successfully building web and android using this action on ubuntu-latest.
I don't understand why but my repo directory is present but empty when i try a iOS build using this yaml:
```yaml
# This is the workflow run for Ios release
name: Ios Release

# Controls when the workflow will run
on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    runs-on: macos-latest
    steps:
      - uses: subosito/flutter-action@v2.4.0
        with:
          flutter-version: '2.10.5'
          channel: stable
          architecture: x64
      - name: Build ios bundle
        run: |
          ls -al
          ls -al ../
          flutter pub get
          flutter analyze
          flutter test
          flutter build ios --obfuscate --split-debug-info=build/app/outputs/symbols --release --no-codesign
```
ls -al returns empty dir
ls -al ../ returns one folder having the name of my repo

Is it an issue coming from that action?
Is there anything I'm missing?
