### ISSUE TITLE
How to cache flutter action env.

### ISSUE THREAD

**Issue by CaiJingLong** [subosito/flutter-action#16]
I see the java and flutter action will use 1min.
![image](https://user-images.githubusercontent.com/14145407/68932216-17f76200-07cd-11ea-98c9-44ddd215b5e7.png)

And I see that the GitHub actions seems to support the cache. 
How can I cache the flutter environment?

**Comment by CaiJingLong** [comment]
[Document of cache](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/caching-dependencies-to-speed-up-workflows)

**Comment by thisismydesign** [comment]
Gave this a try. With the current state of Actions and this action only possible until  v1.2.1 on Ubuntu because of cache size limits. You could build an action which can be cached, details: https://github.com/c-hive/basics/tree/8384a7f41e0045286921c3db11022baa45c73033/flutter-install-cache

Example

`.github/workflows/ci.yml`
```
name: GitHub Actions Workflow with Flutter installation cache

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      flutter_version: "1.2.1"
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Cache Flutter dependencies
        uses: actions/cache@v1
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
```

**Comment by tenhobi** [comment]
Hi, I am trying to get this work. It works great on Ubuntu, but doesn't seems to work on macOS. This is how I do it:

```
jobs:
  # Set up Flutter for all other tasks. a
  setup:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v1
      - name: Cache Flutter dependencies
        uses: actions/cache@v1
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.os }}-flutter
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
```

![image](https://user-images.githubusercontent.com/5287596/72367995-80938a00-36fd-11ea-931f-ff6b4b467d8f.png)
![image](https://user-images.githubusercontent.com/5287596/72367495-92286200-36fc-11ea-8e5c-040c50df9c24.png)

See for example https://github.com/tenhobi/bloc/runs/387885119

Is the path `/opt/hostedtoolcache/flutter` OK for both macOS and Ubuntu?

/Cc @subosito @thisismydesign 

Any ideas? :-)

**Comment by tenhobi** [comment]
OK, it seems that for Ubuntu it is `` but for macOS it is `/Users/runner/hostedtoolcache/flutter/1.12.13-hotfix.5-stable/x64/bin/flutter`. 

Definitely, something to add to README. ;)

**Comment by tenhobi** [comment]
If anyone interested, an example of how to cache Flutter for both Ubuntu and macOS is below.

Note that I am using additional `setup` job, because otherwise eventual parallel jobs (multiple packages, or build task, deploy task etc.) would all do an update and the cache would report a warning etc.

```yaml
name: CI

on: [push]

jobs:
  # Set up Flutter for all other tasks.
  setup:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            flutter_path: /opt/hostedtoolcache/flutter
          - os: macos-latest
            flutter_path: /Users/runner/hostedtoolcache/flutter
      fail-fast: false

    steps:
      - uses: actions/checkout@v1
      - name: Cache Flutter dependencies
        uses: actions/cache@v1
        with:
          path: ${{ matrix.flutter_path }}
          key: ${{ runner.os }}-flutter
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

  # Analyze and test.
  analyze-and-test:
    runs-on: ${{ matrix.os }}
    needs: setup

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            flutter_path: /opt/hostedtoolcache/flutter
          - os: macos-latest
            flutter_path: /Users/runner/hostedtoolcache/flutter
      fail-fast: false

    steps:
      - uses: actions/checkout@v1
      - name: Cache Flutter
        id: cache-flutter
        uses: actions/cache@v1
        with:
          path: ${{ matrix.flutter_path }}
          key: ${{ runner.os }}-flutter
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Analyze and Test
        run: |
          ./tool/ci.sh
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info
```

**Comment by thisismydesign** [comment]
I don't understand how you're not running into the cache size issue with this...

https://github.com/tenhobi/bloc/runs/387881247:
```
Cache Flutter dependencies
Cache restored from key: Linux-flutter
Run actions/cache@v1
Cache Size: ~589 MB (617421119 B)
```

https://help.github.com/en/actions/automating-your-workflow-with-github-actions/caching-dependencies-to-speed-up-workflows:
> Individual files in a cache don't exceed 400 MB. You will receive a 400 - Bad Request if you exceed this limit.

Regarding

> Note that I am using additional setup job, because otherwise eventual parallel jobs (multiple packages, or build task, deploy task etc.) would all do an update and the cache would report a warning etc.

As your key doesn't change (`key: ${{ runner.os }}-flutter`) they won't do an update on the cache. Actually, that way your cache will get outdated and unusable (but will still take time loading) once the flutter version to be installed changes from the one you created the cache with. This is why I have `key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}`. So that when the `flutter_version` to be installed changes it will create a new cache.

**Comment by thisismydesign** [comment]
Seems to be this job where the cache is saved the first time: https://github.com/tenhobi/bloc/commit/4e3a41b74b355d9e7a6e7266044954392cf8641f/checks?check_suite_id=398417991#step:8:3

I think this might be a silent change in GH's side or even bug, in your position I would check with them to make sure this setup will continue to work in the future. According to the docs it shouldn't and might break without notice.

**Comment by tenhobi** [comment]
@thisismydesign it's 2 GB now. https://github.com/actions/cache/releases/tag/v1.1.0

Oh, you are probably right about the keys. Is there a way to download automatically the latest version of Flutter, and not to input it manually?

**Comment by tenhobi** [comment]
Btw. any idea why it's 500 MB in Ubuntu but 1000 MB in macOS?

**Comment by thisismydesign** [comment]
> Oh, you are probably right about the keys. Is there a way to download automatically the latest version of Flutter, and not to input it manually?

That would be the way you're doing it, but you'd need access to the version _before_ that script even runs (to set the key), so I think it has to come from the outside. If you want to go all-out you can make a script that e.g. fetches the latest version and then uses that explicitly in both places. However, framework versions are usually fixed, aren't they?

> Btw. any idea why it's 500 MB in Ubuntu but 1000 MB in macOS?

Not really, it's also a lot more on Windows. Luckily you're still within the 2GB repo limit. Doing all 3 OS would then mean that the cache would ping-pong between them.

**Comment by thisismydesign** [comment]
Cool, so this seems working now, here's our workflow with format, lint, test and build steps: https://github.com/c-hive/basics/blob/7bbebe53a30d8f4066566a16b965dba7683d9b64/.github/workflows/flutter-basics.yml

Pub packages are not handled in this cache though (only the installation), so that should be set up separately.

**Comment by tenhobi** [comment]
Don't you need some first setup task, like I have, to prevent race conditions? See https://github.com/actions/cache/issues/65#issuecomment-551201315

Also, you would have to change the version every time, right? Flutter evolves quite fast, so it might not be the best way...

**Comment by thisismydesign** [comment]
For the first run of the workflow, none of the jobs will use the cache and the first job to finish will save it, the others will print a warning, as the cache with that kay already exists. That's ok. From that moment on all parallel jobs can use the same cache.

> Also, you would have to change the version every time, right? Flutter evolves quite fast, so it might not be the best way...

Yes. Well, it can break fast then, too. Usually, framework versions are fixed across all environments (dev's machines, CIs, test systems, etc) to get rid of environment-related issues. I don't know much about Flutter but that's usually a good approach across the board.

**Comment by qimingweng** [comment]
OK, I've implemented a modified version of @thisismydesign's implementation

- Cache size is about 1GB
- Build times for the Flutter step (subosito/flutter-action@v1) are now around 1minute +- a few seconds

...Is this normal?

**Comment by tenhobi** [comment]
@qimingweng We have this workflow https://github.com/felangel/bloc/blob/master/.github/workflows/main.yaml. Restoring cache takes around 1 minute. The Flutter step is 0s.

**Comment by qimingweng** [comment]
@tenhobi Ok makes sense, and you are correct, is it the cache restore step that takes about 1 minute, not the build. Just wanted to do a sanity check to see if that was about the right time as 1 minute seems both kinda long but also kinda reasonable to fetch 1GB of stuff.

**Comment by thisismydesign** [comment]
There's an issue to get Dart natively on runners: https://github.com/actions/virtual-environments/issues/107

**Comment by ajain-bst** [comment]
My config looks quite similar to the ones mentioned on this thread which supposedly work, but still caching is not working for me.
I keep getting:

`Cache not found for input keys: Linux-flutter-install-cache-1.20.x`

This is the config:

```
name: Flutter CI

on:
  push:
    branches:
      - linter

env:
  flutter_version: "1.20.x"
  java_version: "12.x"

jobs:
  format-and-lint:
    name: Code linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java_version }}
      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
      - name: Flutter analyzer
        run: cd GameTvFlutter && set -o pipefail ; flutter analyze 2&>1 | tee ./ci.txt ; set +o pipefail
```

**Comment by jangruenwaldt** [comment]
I'm using it on macOS but get this error: 
`Warning: The cache content was partially missing or did not match the expected size.`

I'm assuming the flutter directory is too large. I will try splitting up the cache.

My setup:
```
      - name: Cache Flutter
        id: cache-flutter
        uses: actions/cache@v1
        with:
          path: ${{ env.FLUTTER_ROOT }}
          key: ${{ env.FLUTTER_ROOT }}
      - uses: subosito/flutter-action@v1
        timeout-minutes: 5 # sometimes gets stuck
        with:
          channel: 'stable' # or: 'dev' or 'beta'
```
