### ISSUE TITLE
Error when running it: /Users/runner/work/_actions/subosito/flutter-action/v2/setup.sh: line 59: /Users/runner/work/_temp/: Is a directory

### ISSUE THREAD

**Issue by fzyzcjy** [subosito/flutter-action#169]
See here for full github action run: https://github.com/fzyzcjy/flutter_rust_bridge/runs/6871188630?check_suite_focus=true

```
Run subosito/flutter-action@v2
  with:
    channel: stable
    architecture: x64
    flutter-version: any
    cache-key: flutter
    cache-path: /Users/runner/hostedtoolcache/flutter
  env:
    CARGO_TERM_COLOR: always
Run $GITHUB_ACTION_PATH/setup.sh -c "/Users/runner/hostedtoolcache/flutter" stable any x64
  $GITHUB_ACTION_PATH/setup.sh -c "/Users/runner/hostedtoolcache/flutter" stable any x64
  shell: /bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    CARGO_TERM_COLOR: always
usage: basename string [suffix]
       basename [-a] [-s suffix] string [...]
/Users/runner/work/_actions/subosito/flutter-action/v[2](https://github.com/fzyzcjy/flutter_rust_bridge/runs/6871188630?check_suite_focus=true#step:4:2)/setup.sh: line [5](https://github.com/fzyzcjy/flutter_rust_bridge/runs/6871188630?check_suite_focus=true#step:4:5)[9](https://github.com/fzyzcjy/flutter_rust_bridge/runs/6871188630?check_suite_focus=true#step:4:9): /Users/runner/work/_temp/: Is a directory
tar: Error opening archive: Error reading '/Users/runner/work/_temp/'
rm: /Users/runner/work/_temp/: is a directory
```
