### ISSUE TITLE
Flutter Analyze fails for 'firebase_options.dart'

### ISSUE THREAD

**Issue by OutdatedGuy** [subosito/flutter-action#172]
I'm using `firebase_options.dart` to configure my flutter app with firebase. But on GitHub I've put that file in `.gitignore`.

So to use it in GitHub actions, I'm creating the file then adding it's contents from GitHub secrets.
The file is created successfully with correct data.

However, when I run `flutter analyze .` it throws error that
![image](https://user-images.githubusercontent.com/74326345/179371599-80e6f9a2-dbd0-469b-aab5-2d62a7873020.png)

## Workflow File
```yml
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter --version

      # Create firebase_options.dart file with valid data
      - name: Write firebase_options.dart
        env:
          FIREBASE_OPTIONS: ${{ secrets.FIREBASE_OPTIONS }}
        run: |
          touch lib/firebase_options.dart
          echo $FIREBASE_OPTIONS >> lib/firebase_options.dart
          cd lib
          ls
          cat firebase_options.dart
      # Get flutter dependencies.
      - name: Install dependencies
        run: flutter pub get

      # Check for any formatting issues in the code.
      - name: Verify formatting
        run: flutter format --set-exit-if-changed .

      # Statically analyze the Dart code for any errors.
      - name: Analyze project source
        run: flutter analyze .
```
