### ISSUE TITLE
x64 install using flutter-action@v2 won't install a flutter version higher than 3.0.1

### ISSUE THREAD

**Issue by charlesluzar** [subosito/flutter-action#177]
I'm trying to get this action to install Flutter@3.0.5 but it won't seem to install anything higher than 3.0.1 on a `macos` VM running the `self-hosted` actions runner. 

Things I tried:
- `architecture` with and without quotes
- `x64` and `arm64` architectures
- `flutter-version` without `channel` and vice-versa
- Running against `subosito/flutter-action@v1`

Nothing I tried got anything higher than 3.0.1 to install.

Here's a script I used to test on a `macos` machine:

```yaml
steps:
  - name: Prove we only have a stock macos dart SDK
    run: which dart
  - name: Prove we don't have a flutter SDK yet
    run: which flutter
    continue-on-error: true
  - uses: actions/setup-java@v1
    with:
      java-version: "12.x"
  - uses: subosito/flutter-action@v2
    with:
      flutter-version: "3.0.5"
      channel: "stable"
      architecture: x64
  - name: Prove subosito/flutter-action@v2 persisted the new dart SDK to $PATH
    run: which dart
  - name: Prove subosito/flutter-action@v2 persisted the new flutter SDK to $PATH
    run: which flutter
  - name: Prove we have the wrong version of the flutter and dart SDKs
    run: flutter doctor
```

Here is the output. (If you'd like the raw logs just let me know, I figured this is easier to look at.)

![image](https://user-images.githubusercontent.com/65074/180864204-46b88fca-7391-4a35-a0ff-5fd572dfb61a.png)
