### ISSUE TITLE
`dart --version` is not working!

### ISSUE THREAD

**Issue by KKimj** [subosito/flutter-action#178]
![image](https://user-images.githubusercontent.com/40026920/180948594-b4514134-58b0-4180-8895-2afe934aa6f3.png)

```yaml

jobs:
  flutter_lint_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        flutter-project-dir: [
          ./packages/flutter_example
        ]
        flutter-channel: [ stable ]
        flutter-version: [ 3.0.0 ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter-version }}
          channel: ${{ matrix.flutter-channel }}
          cache: true

      - name: Check up SDKs
        run: |
          dart --version
          flutter --version

```

Hello, There is a issue with `dart --version`!

Thanks!

Have a Nice Day!
