### ISSUE TITLE
Action is suddenly failing

### ISSUE THREAD

**Issue by GabrielBB** [subosito/flutter-action#180]
I get:
![image](https://user-images.githubusercontent.com/8752823/180974084-862ea7a2-f3cc-4784-8207-f91b2635992e.png)

When using:

```
- name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.0.5"
          channel: "stable"
          cache: true
```
