### ISSUE TITLE
Make inputs.cache have a default value

### ISSUE THREAD

**Issue by VoidxHoshi** [subosito/flutter-action#182]
```
  flutter-version:
    description: 'The Flutter version to make available on the path'
    required: false
    default: 'any'
  channel:
    description: 'The Flutter build release channel'
    required: false
    default: 'stable'
  cache:
    description: 'Cache the Flutter SDK'
    required: false
  cache-key:
    description: 'Identifier for the Flutter SDK cache'
    required: false
    default: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
  cache-path:
    description: 'Flutter SDK cache path'
    required: false
    default: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:'
  architecture:
    description: 'The architecture of Flutter SDK executable (x64 or arm64)'
    required: false
    default: ${{ runner.arch }}
```
While all other inputs have a default value, `cache`, an important input, cannot be `null`.
The default should be `false`.
