### ISSUE TITLE
commit 9d48f4e no longer resolves environment variables passed in

### ISSUE THREAD

**Issue by jorgenpt** [subosito/flutter-action#184]
Running the flutter-action after commit 9d48f4e fails (tested on a ubuntu-latest runner):

```
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
stable:$FLUTTER_VERSION:x64|null:null:x64
```

It looks like it's no longer resolving the `$FLUTTER_VERSION` variable I pass in.

Also worth noting that this `tar` failure did *not* fail the action, so the actual failure was the next step trying to run `flutter pub get` and getting `/home/runner/work/_temp/10150038-ae3e-4950-be3c-f4528f6fab2e.sh: line 1: flutter: command not found`

Here's the [full log output](https://github.com/subosito/flutter-action/files/9427375/log.txt)

Here's the the relevant workflow snippet:

```yaml
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          flutter-version: $FLUTTER_VERSION
```

If I lock the action version to the prior commit with the following snippet, it works as expected:

```yaml
      - name: Setup flutter
        uses: subosito/flutter-action@6c2e035f2692eeac890d854df95630c72673f130
        with:
          cache: true
          flutter-version: $FLUTTER_VERSION
```
