### ISSUE TITLE
feat: add  cache restore keys option

### ISSUE THREAD

**Issue by renancaraujo** [subosito/flutter-action#195]
Cache restore-keys options [allow the cache to be restored even when they are invalidated in some cases](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#input-parameters-for-the-cache-action).

For a scenario where one uses a custom `cache-key` that includes lock files, a restore-key would be almost always necessary.

```yaml
     - name: 🐦 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.3.3
          channel: stable
          cache: true
          cache-key: flutter-:os:-:channel:-:version:-:arch:-:hash:-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            flutter-:os:-:channel:-:version:-:arch:-:hash:-${{ hashFiles('**/pubspec.lock') }}
            flutter-:os:-:channel:-:version:-:arch:-:hash
```
