### ISSUE TITLE
Bug makes it think 3.3.1 refers to 3.3.10?

### ISSUE THREAD

**Issue by noga-dev** [subosito/flutter-action#199]
My pipe seems to fail and shows 3.3.10 being used instead of 3.3.1 even thought I have this in my workflow:
```
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.1' # <<< bug makes it think 3.3.1 refers to 3.3.10?
          channel: 'stable'
```
