### ISSUE TITLE
Infer Flutter version from `pubspec.yaml`

### ISSUE THREAD

**Issue by bartekpacia** [subosito/flutter-action#211]
I find it a bit annoying that whenever I update Flutter, I have to change the version in `pubspec.yaml` and in my GitHub Actions workflows.

I think it'd be great if this action would infer Flutter version from `pubspec.yaml`:

```yaml
- name: Set up Flutter
  uses: subosito/flutter-action@v2
  with:
    channel: stable
    # flutter-version: '3.7.0' # not needed - automatically infers from `pubspec.yaml`
    architecture: x64
    cache: true
```

This approach is used in, for example, the [actions/setup-go](https://github.com/actions/setup-go):

```yaml
  - uses: actions/setup-go@v4
    with:
      go-version-file: go.mod
```

Of course, it'd still be possible to explicitly specify the Flutter version to use.
