### ISSUE TITLE
 Invalid argument on Mac worker

### ISSUE THREAD

**Issue by darhaywa** [subosito/flutter-action#226]
When `setup.sh` runs the following error occurs

```
mv: rename /Users/<username>/Applications/actions-runner/_work/_temp/flutter to /Users/<username>/Applications/actions-runner/_work/_temp/flutter/stable-3.10.0-x64: Invalid argument
```

It is not possible to move/rename a directory to a child of the directory being moved on a Mac running the following causes the same problem
```
mkdir temp
mv temp temp/test
```

It looks like this [line](https://github.com/subosito/flutter-action/blob/48cafc24713cca54bbe03cdc3a423187d413aafa/setup.sh#L90) should not be using RUNNER_TEMP

Configuration in action
```
name: Prepare Flutter environment

description: Prepare Flutter environment

runs:
  using: "composite"
  steps:
    - uses: subosito/flutter-action@v2
```
