### ISSUE TITLE
Jq is installed on self-hosted runner, but not detected

### ISSUE THREAD

**Issue by pattersonjack** [subosito/flutter-action#238]
We previously had our runner script working on an Intel iMac. However, now that we have migrated to an M2 Mac Mini, we have begun receiving this error:

```
Run $GITHUB_ACTION_PATH/setup.sh -p -c '/Users/runner/actions-runner/_work/_tool/flutter/:channel:-:version:-:arch:' -k 'flutter-:os:-:channel:-:version:-:arch:-:hash:' -n '3.10.5' -a 'ARM64' stable
  $GITHUB_ACTION_PATH/setup.sh -p -c '/Users/runner/actions-runner/_work/_tool/flutter/:channel:-:version:-:arch:' -k 'flutter-:os:-:channel:-:version:-:arch:-:hash:' -n '3.10.5' -a 'ARM64' stable
  shell: /bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    JAVA_VERSION: 11.x
    FLUTTER_VERSION: 3.10.5
jq not found, please install it, https://stedolan.github.io/jq/download/
Error: Process completed with exit code 1.
```

This is all we have in the failing step:

```
- name: Set up the Flutter environment
  uses: subosito/flutter-action@v2
  with:
    flutter-version: ${{env.FLUTTER_VERSION}}
    channel: 'stable'
```

Jq is installed on our system (using brew) and it can be found and used normally by the correct user. The shell this action runs in includes both `--noprofile` and `--norc`. Does this impact whether homebrew and its installed packages are included in the PATH when the action is executed?

If not, is there anything else needed to ensure jq is correctly detected?
