### ISSUE TITLE
Cannot build a new veresion for specified stable version for flutter 

### ISSUE THREAD

**Issue by YeFei572** [subosito/flutter-action#240]
the warning message:
```shell
[build](https://github.com/YeFei572/flutter_cim_plus/actions/runs/5759428325/job/15613512744#logs)
failed 1 hour ago in 1m 4s
Search logs
3s
0s
5s
38s
16s
1s
Run flutter build apk --target-platform=android-arm64

Running Gradle task 'assembleRelease'...                        
Error: Exception in thread "main" java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:579)
	at java.base/sun.nio.ch.Net.connect(Net.java:568)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:593)
	at java.base/java.net.Socket.connect(Socket.java:639)
	at java.base/java.net.Socket.connect(Socket.java:588)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:[1](https://github.com/YeFei572/flutter_cim_plus/actions/runs/5759428325/job/15613512744#step:6:1)83)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:533)
	at java.base/sun.net.www.http.HttpClient$1.run(HttpClient.java:5[9](https://github.com/YeFei572/flutter_cim_plus/actions/runs/5759428325/job/15613512744#step:6:10)2)
	at java.base/sun.net.www.http.HttpClient$1.run(HttpClient.java:590)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at java.base/sun.net.www.http.HttpClient.privilegedOpenServer(HttpClient.java:589)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:633)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:202)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1266)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:[11](https://github.com/YeFei572/flutter_cim_plus/actions/runs/5759428325/job/15613512744#step:6:12)31)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1668)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1592)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
	at org.gradle.wrapper.Download.download(Download.java:44)
	at org.gradle.wrapper.Install$1.call(Install.java:61)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Running Gradle task 'assembleRelease'...                           304ms
Gradle task assembleRelease failed with exit code 1
Error: Process completed with exit code 1.
```

and the dart.yaml file is:

```yaml
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        # 创建 java 环境
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"
          token: ${{ secrets.ACTION_TOKENS }}
      # 创建 Flutter 环境
      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.5"
          channel: "stable"
        # 下载项目依赖
      - run: flutter pub get
      - run: flutter build apk --target-platform=android-arm64
      # 发布到 Release
      - name: Release apk
        uses: ncipollo/release-action@v1.5.0
        with:
          artifacts: "build/app/outputs/apk/release/*.apk"
          token: ${{ secrets.ACTION_TOKENS}}
```

Pls help me, thx

**Comment by mizzouliger** [comment]
There is a workaround. I used version 3.10.6. Which was the last stable version.

I do not believe there is a 3.10.5. But it worked as the one above. @YeFei572

**Comment by YeFei572** [comment]
@mizzouliger Do you know if the bug is a dependency or a version of the SDK?

I have tried 3.10.6, but it doesn't work.

these is my dependencies:

```yaml
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.8.4
  easy_refresh: ^3.3.2+1
  get: ^4.6.5
  dio: ^5.2.0+1
  cached_network_image: ^3.2.3
  json_annotation: ^4.8.1
  flutter_login: ^4.1.1
  get_storage: ^2.1.1
  sprintf: ^7.0.0
  logger: ^1.4.0
  retrofit: ^4.0.1
  pretty_dio_logger: ^1.3.1
  fluttertoast: ^8.2.2
  socket_io_client: ^2.0.2
  fixnum: ^1.1.0
  protobuf: ^2.1.0
  sqflite: ^2.2.8+4
  # 使Ink没有水波纹
  flutter_bounce: ^1.1.0
  scrollview_observer: ^1.15.0
  path:
```
