### ISSUE TITLE
Got error when using it

### ISSUE THREAD

**Issue by Mister-Hope** [subosito/flutter-action#25]
My workflow

```yml
name: Flutter test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: google/dart:latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Install dependencies
        run: flutter pub get
      - name: Run tests
        run: pub run test
```

Result

```
 Run subosito/flutter-action@v13s
##[error]The process '/usr/bin/tar' failed with exit code 2
Run subosito/flutter-action@v1
/usr/bin/docker exec  e96d380970b9fa8c036bc079c8d0da8dd2dc356344626e92d74d60e120268fc3 sh -c "cat /etc/*release | grep ^ID"
Running JavaScript Action with default external tool: node12
/usr/bin/tar --version
tar (GNU tar) 1.30
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
/usr/bin/tar x --warning=no-unknown-keyword -C /__w/_temp/temp_1883226862 -f /__w/_temp/aab85ca5-43e9-4ca2-b9c7-24841ffa87ce
tar (child): xz: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
/usr/bin/tar: Child returned status 2
/usr/bin/tar: Error is not recoverable: exiting now
##[error]The process '/usr/bin/tar' failed with exit code 2
```

What's wrong with it?
