### ISSUE TITLE
Flutter Cache Not Working

### ISSUE THREAD

**Issue by tcf909** [subosito/flutter-action#250]
Hello,

When trying to use cache: true I see this in the post hooks (and caching never seems to actually work): 

![image](https://github.com/subosito/flutter-action/assets/1562915/10511644-13c1-4fed-a8ae-b1264791d1f8)

Composite action def: 
```
runs:
  using: 'composite'
  steps:
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: '3.10.6'
        cache: true
        #cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:' # optional, change this to force refresh cache
        #cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:' # optional, change this to specify the cache path
```

This is on both ubuntu-latest and macos-13
