### ISSUE TITLE
Allow to automatically run `flutter precache`

### ISSUE THREAD

**Issue by bartekpacia** [subosito/flutter-action#256]
I often have the following code in my workflows

```yaml
- name: Set up Flutter
  uses: subosito/flutter-action@v2
  with:
    flutter-version: ${{ matrix.flutter-version }}
    channel: ${{ matrix.flutter-channel }}

- name: Preload Flutter artifacts
  run: flutter precache
```

I wish I could so something like:

```yaml
- name: Set up Flutter
  uses: subosito/flutter-action@v2
  with:
    flutter-version: ${{ matrix.flutter-version }}
    channel: ${{ matrix.flutter-channel }}
    precache: true
```

Possibly it should also allow for more granular selection of artifacts to precache, e.g. `flutter precache --android --ios` would translate to:

```yaml
- name: Set up Flutter
  uses: subosito/flutter-action@v2
  with:
    flutter-version: ${{ matrix.flutter-version }}
    channel: ${{ matrix.flutter-channel }}
    precache: ['android', 'ios']
```

**Comment by subosito** [comment]
I like this idea @bartekpacia, I would be happy to merge the PR.

**Comment by bartekpacia** [comment]
awesome, I'll start on it :)

**Comment by bartekpacia** [comment]
GitHub Actions doesn't support passing arrays to actions. For example, I would want to have this API:

```yaml
- name: Set up Flutter
  uses: subosito/flutter-action@v2
  with:
    channel: stable
    flutter-version: '3.19.0'
    precache: [android, ios]
```

but it doesn't work:

<img width="470" alt="Screenshot 2024-03-02 at 04 36 11" src="https://github.com/subosito/flutter-action/assets/40357511/dbca785c-751a-4790-9c55-48c9c78a827e">

Only strings, integers, or booleans can be passed, so that's how actually the API would look like:

```yaml
- name: Set up Flutter
  uses: subosito/flutter-action@v2
  with:
    channel: stable
    flutter-version: '3.19.0'
    precache: '[android, ios]'
```

I think it's pretty ugly. So right now I'm leaning toward making `precache` a boolean.

```yaml
- name: Set up Flutter
  uses: subosito/flutter-action@v2
  with:
    channel: stable
    flutter-version: '3.19.0'
    precache: true
```

Someone can contribute the more complex version later, and meanwhile they can continue with calling `flutter precache` manually.

**Comment by yurikoles** [comment]
What about nested booleans?
```yml
precache:
  ios: true
  android: false
```
