### ISSUE TITLE
Build fails on 3.16.0 on iOS

### ISSUE THREAD

**Issue by rayyan808** [subosito/flutter-action#259]
My flutter project will compile and run perfectly on Android and iOS from our development MacBooks. But it fails the build test on GitHub Workflows only for iOS:
```

name: CI Workflow
on:
  push:
    branches: [main, stage]
  pull_request:
    branches: [dev]
jobs:
  android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
    - run: flutter pub get
    #- run: flutter test
    - run: flutter build apk
    - run: flutter build appbundle
  apple:
    name: Build iOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        architecture: x64
    - run: flutter pub get
    #- run: flutter test
    - run: flutter build ios --release --no-codesign

```
```

 Unhandled exception:
    Null check operator used on a null value
    #0      Context.embedFlutterFrameworks (file:///Users/runner/hostedtoolcache/flutter/stable-3.16.1-x64/packages/flutter_tools/bin/xcode_backend.dart:235:68)
    #1      Context.run (file:///Users/runner/hostedtoolcache/flutter/stable-3.16.1-x64/packages/flutter_tools/bin/xcode_backend.dart:59:9)
    #2      main (file:///Users/runner/hostedtoolcache/flutter/stable-3.16.1-x64/packages/flutter_tools/bin/xcode_backend.dart:17:5)
    #3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
    #4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
    Command PhaseScriptExecution failed with a nonzero exit code
```
