### ISSUE TITLE
How to integrate with caching

### ISSUE THREAD

**Issue by niccokunzmann** [subosito/flutter-action#283]
For caching, I see this section:

```
Integration with actions/cache:
```

What I do not know is the following:
- Is that all the code that I need?
- Do I need to configure caching paths before this?
- What benefit does it have to cache?
- Is caching enabled by default or not?

**Comment by bartekpacia** [comment]
If you want to take advantage of caching, you just need to set `cache: true`:

```yaml
- name: Set up Flutter
  uses: subosito/flutter-action@v2
  with:
    channel: stable
    flutter-version: 3.19.0
    precache: true # <--
```

**Comment by niccokunzmann** [comment]
Uh, I just created #284 and I wonder what the difference between `precache` and `cache` is.

**Comment by bartekpacia** [comment]
Ugh, my bad!

**Comment by bartekpacia** [comment]
I meant this:

```yaml
- name: Set up Flutter
  uses: subosito/flutter-action@v2
  with:
    channel: stable
    flutter-version: 3.19.0
    cache: true # <--
```
