### ISSUE TITLE
How to install flutter 2 on an Apple Silicon runner images?

### ISSUE THREAD

**Issue by guilhermearaujo** [subosito/flutter-action#297]
I have this project that still runs flutter 2.10.5, but I cannot get the action to install this version on the new runner images that run on Apple Silicon (`macos-14` which is rolling out as `macos-latest`)

When the action run, it fails with:
> Unable to determine Flutter version for channel: stable version: 2.10.5 architecture: arm64

How can I force the action to run with Rosetta 2?

**Comment by bartekpacia** [comment]
AFAIK, Flutter version before 3.0 didn't run natively on arm64. They were running on Rosetta.

[(source 1)](https://medium.com/simform-engineering/flutter-3-0-is-here-heres-all-you-need-to-know-95db32f62d24) [(source 2)](https://somniosoftware.com/blog/flutter-3-0-announcement-at-google-i-o)

**Comment by guilhermearaujo** [comment]
Exactly, but is it possible to use this action to download the amd64 and run it through Rosetta?

**Comment by bartekpacia** [comment]
Set architecture to `arm64` instead of `amd64`:

```yaml
- name: Set up Flutter
  uses: subosito/flutter-action@v2
  with:
    channel: stable
    version: 2.10.x
    architecture: amd64
```
