### ISSUE TITLE
Allow for specifying only MAJOR.MINOR Flutter version (without the "x" suffix)

### ISSUE THREAD

**Issue by bartekpacia** [subosito/flutter-action#298]
Allow for specifying Flutter version like this:

```yaml
- name: Set up Flutter
  uses: subosito/flutter-action@v2
  with:
    channel: stable
    flutter-version: 3.19.x
```

in addition to the aleady supported:

```yaml
- name: Set up Flutter
  uses: subosito/flutter-action@v2
  with:
    channel: stable
    flutter-version: 3.19.x
```
