### ISSUE TITLE
Add support for Flutter version ranges

### ISSUE THREAD

**Issue by bartekpacia** [subosito/flutter-action#299]
As a plugin maintainer, I want to run my CI to test/analyze/format my plugin against Flutter version it supports.

For example, let's say my plugin supports at least Flutter 3.10.0, so I'll have this in `pubspec.yaml`:

```yaml
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"
```

In my GitHub Actions, I have this:

```yaml
jobs:
  main:
    name: Flutter ${{ matrix.flutter-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        flutter-version: ["3.10.x", "3.13.x", "3.16.x", "3.19.x"]

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ matrix.flutter-version }}
```

Problems with it:
- Whenever I bump the minimum Flutter version, I have to also remove it from CI workflow
- Whenever a new Flutter version is released, I need to remember to add it to CI workflow

### Idea

I suggest addition of `flutter-version-range` and `flutter-version-range-file` property:

```pubspec
- name: Set up Flutter
  uses: subosito/flutter-action@v2
  with:
    channel: stable
    flutter-version-range-file: pubspec.yaml # path to pubspec.yaml
```

Assuming the `pubspec.yaml` defined above, this would return `[3.10.6, 3.13.9, 3.16.9, 3.19.5]` (latest PATCH versions for every MINOR version).

**Except it wouldn't work**, because then we only know the versions at runtime, but to make a matrix build we need to known them statically.

It would also increase complexity of this action.

---

For now, I think the best action forward is to create a script (either Sh/Bash or Dart - the second would be likely much better because the [`pub_semver`](https://pub.dev/packages/pub_semver) package could be used).

Then the CI workflow from above could be split into 2 jobs:
- `job get_flutter_versions`, outputs `[3.10.6, 3.13.9, 3.16.9, 3.19.5]`
- `job main`, gets the versions as input and uses them to create a matrix build
