### ISSUE TITLE
pub cache not found 

### ISSUE THREAD

**Issue by git-elliot** [subosito/flutter-action#300]
https://github.com/osociety/vernet/actions/runs/8645064405/job/23701563442

**Comment by seuros** [comment]
The cache mechanism run twice: 
Run actions/cache@v4
Run actions/cache@v4

**Comment by git-elliot** [comment]
@seuros  It ran twice to cache flutter first and then cache pub dependencies.

**Comment by bartekpacia** [comment]
Hi! Feel free to make a PR with changes you'd like. I'm all for making the logs more descriptive.

**Comment by jencompgeek** [comment]
Hi! I'm running into this exact same issue (same cache not found for input keys and same error in the post action). Was there a resolution for this?

**Comment by bartekpacia** [comment]
probably related to issue #319

**Comment by bartekpacia** [comment]
Fix for #319 was merged and released, please say if this still happens, otherwise I'm going to close this issue soon.

**Comment by Artein** [comment]
For some reason, I stopped seeing this issue after adding this:
```yaml
        name: Restore BuildRunner cache
        uses: actions/cache@v4
        with:
          path: |
            .dart_tool/build
            .dart_tool/flutter_build
          key: ${{ runner.os }}-build-${{ hashFiles('**/pubspec.lock', '**/build.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-
```

GitHub Action: [flutter-tests.yml.txt](https://github.com/user-attachments/files/20649888/flutter-tests.yml.txt)
Run complete log: [job-logs.txt](https://github.com/user-attachments/files/20649861/job-logs.txt)
