### ISSUE TITLE
Windows fails: `bash: command not found`

### ISSUE THREAD

**Issue by tomgilder** [subosito/flutter-action#302]
Hello, my workflow is failing on Windows with `bash: command not found`, here's the error log:

```
Run subosito/flutter-action@v2
  with:
    channel: stable
    architecture: X64
    cache: false
    pub-cache-path: default
    dry-run: false

Run chmod +x "$GITHUB_ACTION_PATH/setup.sh"
  chmod +x "$GITHUB_ACTION_PATH/setup.sh"
  Error: bash: command not found
```

This was reported by someone else in #159.

I'm using a matrix to build on multiple architectures:

```
name: Build

on:
  workflow_call:
    inputs:
      run-tests:
        required: true
        type: boolean
      dry-run:
        required: true
        type: boolean
      pre-release:
        required: true
        type: boolean
      version:
        required: true
        type: string

jobs:
  package_vscode:
    runs-on: ${{ matrix.labels }}

    strategy:
      matrix:
        include:
          - architecture: darwin-arm64
            labels: [self-hosted, macOS, ARM64]
          - architecture: darwin-x64
            labels: [self-hosted, macOS, x64]
          - architecture: win32-x64
            labels: [self-hosted, Windows, x64]

    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
```

Thanks for the great workflow 👍
