### ISSUE TITLE
Remove yq dependency to fetch version from file

### ISSUE THREAD

**Issue by danielgomezrico** [subosito/flutter-action#306]
Hi

Theres a bash way to parse the file and is using grep and awk like:
I use that on my scripts like:

```yaml

      - name: Prepare flutter version from pubspec.yml
        run: |
          $content = Get-Content -Path pubspec.yaml
          $match = [regex]::match($content, 'flutter: (\d+\.\d+\.\d+)')
          echo "FLUTTER_VERSION=$($match.Groups[1].Value)" | Out-File -FilePath $env:GITHUB_ENV -Append
        shell: pwsh

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}
          cache: false
```

Maybe the way that `flutter-version-file` works could change to this to avoid the YQ dependency install on windows, WDYT? can you guide me on how to change that? I could create the PR with that change 🤓
