### ISSUE TITLE
How to apply a patch in flutter directory ?

### ISSUE THREAD

**Issue by Ortes** [subosito/flutter-action#310]
I want to apply a patch from this [PR](https://github.com/flutter/flutter/pull/137874) how to proceed ?
On my local machine i use the following in the flutter directory:

``` bash
curl https://patch-diff.githubusercontent.com/raw/flutter/flutter/pull/137874.patch > intrinsic.patch
git apply intrinsic.patch
```

How can I do the same from my CI ?

**Comment by thaidmfinnick** [comment]
I have a question like you, and I have a workaround, can you try it?
```yaml
jobs:
  auto-build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2'
        channel: 'stable'
        cache: true
    - run: |
        flutter --version
        cd ${{ env.FLUTTER_ROOT }}
        curl https://patch-diff.githubusercontent.com/raw/flutter/flutter/pull/137874.patch | git apply
        git status
```

**Comment by bartekpacia** [comment]
hey!

@Ortes, this is an excellent question!

@thaidmfinnick, this is an excellent answer! I think it's good enough and there's no need for modifying code of the action itself.

I'm going to include this in the README so it's more easily accessible to people who might want to do the same.

**Comment by bartekpacia** [comment]
Linked to this issue from README in #337.

**Comment by munrocket** [comment]
If you using stable flutter you need to make patch by yourself
```sh
git checkout `stable`
git cherry-pick -n `PR`
git diff --cached > flutter.patch
```
Store it in your repo and try this after install
```yaml
- name: Patch flutter
  run: |
    cd ${{ env.FLUTTER_ROOT }}
    git apply ~/work/your-repo/your-repo/flutter.patch
- name: Use flutter
  run: flutter run

- name: Update tools
  run: cd ${{ env.FLUTTER_ROOT }}/packages/flutter_tools && flutter pub get 
- name: Use flutter with updated tools
  run: flutter-dev drive
```
