### ISSUE TITLE
Check master branch if not found in 'any' channel

### ISSUE THREAD

**Issue by ThomasAunvik** [subosito/flutter-action#312]
Attempted to use a tag for the master branch, but when i used `any` as the channel, it fails to find.

`Unable to determine Flutter version for channel: any version: 3.23.0-12.0.pre architecture: x64`

```yml
- name: Flutter Environment
        uses: subosito/flutter-action@v2.16.0
        with:
          channel: any
          flutter-version-file: pubspec.yaml
```

Changing it to `master` works good, but would rather choose when to use stable or master in the yaml file if i could.

pubspec:
```yaml
environment:
  sdk: ^3.3.4
  flutter: 3.23.0-12.0.pre
```
