### ISSUE TITLE
Windows setup fails on beta channel

### ISSUE THREAD

**Issue by NobodyForNothing** [subosito/flutter-action#315]
A workflow like the one from the example fails on windows:
```yaml
windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
      - run: flutter build windows --release
```

After downloading the following error is displayed in [the log](https://github.com/NobodyForNothing/pluggy/actions/runs/9429194566/job/25975323970):
```
flutter/docs/engine/ci/Engine-pre‐submits-and-post‐submits.md:  mismatching "local" filename (flutter/docs/engine/ci/Engine-pre���submits-and-post���submits.md),
         continuing with "central" filename version
```
