### ISSUE TITLE
flutter action using self hosted  runners in github  enterprise  account , unable to run my workflow 

### ISSUE THREAD

**Issue by vijaymsc** [subosito/flutter-action#322]
```
name: Flutter CI

# This workflow is triggered on pushes to the repository.

on:
  push:
    branches:
      - cicd_dev

    # on: push    # Default will running for every branch.

jobs:
  build:
    # This job will run on ubuntu virtual machine
    runs-on: self-hosted
    steps:

      # Setup Java environment in order to build the Android app.
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      # Setup the flutter environment.
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v2.16.0
        with:
          flutter-version: 3.22.2
      - run: flutter pub get
      - run: flutter build apk --release --flavor prod


      # Upload generated apk to the artifacts.
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
```
