### ISSUE TITLE
flutter-version-file: pubspec.yaml wrongly resolving flutter version ?

### ISSUE THREAD

**Issue by pierrecorsini** [subosito/flutter-action#328]
Hi

Action
```
 - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version-file: pubspec.yaml
```

Pubspec docs (https://docs.flutter.dev/tools/pubspec)
```
environment:
  sdk: ^3.5.0

```

setup.sh
`VERSION="$(yq '.environment.flutter' "$VERSION_FILE")"`

I do think `setup.sh` searches in `environment.flutter` whereas it should be searching in `environment.sdk`.

**Comment by pierrecorsini** [comment]
```
Good

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: 3.19.0
```

This is well documented , my bad. Closed.
