### ISSUE TITLE
Support New Release Version Format

### ISSUE THREAD

**Issue by felangel** [subosito/flutter-action#34]
The flutter release tag format has changed to exclude the `v` prefix so the following fails to find the release

```yaml
with:
  flutter-version: "1.17.0-dev.3.0"
  channel: beta
```

It is looking for `beta/macos/flutter_macos_v1.17.0-dev.3.1-beta.zip` instead of `beta/macos/flutter_macos_1.17.0-dev.3.1-beta.zip` in https://storage.googleapis.com/flutter_infra/releases/releases_macos.json.

I think it would be more robust to just take the exact `flutter-version` specified instead of having the action manipulate it internally.
