### ISSUE TITLE
  **flutter: 3.19.0** and          flutter-version-file: pubspec.yaml  dont work

### ISSUE THREAD

**Issue by wanghaisheng** [subosito/flutter-action#340]
```
name: Build and Deploy PWA to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version-file: pubspec.yaml # path to pubspec.yaml

    - name: Install dependencies
      run: flutter pub get

    - name: Generate firebase_options.dart
      run: flutterfire configure --platforms=web

    - name: Generate env.g.dart
      run: dart run build_runner build --delete-conflicting-outputs

    - name: Build Flutter web
      run: flutter build web --release

    - name: Deploy to GitHub Pages
      run: |
        # Configure the deployment directory and branch
        mv build/web out
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

        # Check if the gh-pages branch exists and create it if it doesn't
        if ! git show-ref --quiet refs/heads/gh-pages; then
          git checkout --orphan gh-pages
          git rm -rf .
          touch README.md
          git add README.md
          git commit -m "Initialize gh-pages branch"
          git push origin gh-pages
        fi

        # Switch to the gh-pages branch and deploy the built files
        git checkout gh-pages
        rm -rf *
        cp -r ../out/* .
        git add .
        git commit -m "Deploy to GitHub Pages"
        git push --force origin gh-pages

    - name: Clean up
      run: rm -rf out
```

```
name: applimode_app
description: My Applimode Project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.2.5+1

environment:
  sdk: '>=3.1.5 <4.0.0'
  **flutter: 3.19.0**

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.0.1
  firebase_messaging: ^15.0.1
  cloud_functions: ^5.0.1
  firebase_ui_auth: ^1.15.0
  firebase_ui_localizations: ^1.12.0
  firebase_vertexai: ^1.0.1

  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter

  web: ^1.0.0
  go_router: ^14.0.2
  equatable: ^2.0.5
  flutter_riverpod: ^2.4.5
  riverpod_annotation: ^2.3.0

  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  flutter_markdown: ^0.7.1
  markdown: ^7.1.1

  uuid: ^4.2.1
  shared_preferences: ^2.2.2
  flutter_native_splash: ^2.3.5
  video_player: ^2.8.1
  url_launcher: ^6.2.1
  http: ^1.1.2
  dio: ^5.4.0
  envied: ^1.0.0
  wakelock_plus: ^1.1.4
  path: ^1.9.0
  path_provider: ^2.1.5
  fc_native_video_thumbnail: ^0.16.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  riverpod_lint: ^2.3.10
  custom_lint: ^0.7.0
  riverpod_generator: ^2.4.0
  flutter_launcher_icons: ^0.14.1
  envied_generator: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

error

```
The current Dart SDK version is 3.3.0.
Because flutter_lints 5.0.0 requires SDK version ^3.5.0 and no versions of flutter_lints match >5.0.0 <6.0.0, flutter_lints ^5.0.0 is forbidden.

```
