### ISSUE TITLE
Using flutter-version-file: on a self-hosted runner doesn't work

### ISSUE THREAD

**Issue by d-walsh** [subosito/flutter-action#342]
I get this error:

```
Run subosito/flutter-action@v2
  with:
    channel: stable
    flutter-version-file: pubspec.yaml
    cache: true
    architecture: X64
    pub-cache-path: default
    dry-run: false
Run chmod +x "$GITHUB_ACTION_PATH/setup.sh"
Run $GITHUB_ACTION_PATH/setup.sh -p \
Unable to determine Flutter version for channel: stable version: "3.27.1" architecture: x64
``` 

it works fine when I use the github hosted runners though (eg. ubuntu-latest).
