### ISSUE TITLE
pub-cache-key

### ISSUE THREAD

**Issue by altanodm** [subosito/flutter-action#344]
Hello.

i want to use static pub-cache-key. But current action is [${{  }}](key: ${{ steps.flutter-action.outputs.PUB-CACHE-KEY }}-${{ hashFiles('**/pubspec.lock') }}).

Please change this cache key

**Comment by subosito** [comment]
Hi @altanodm 

You can always override the options:

```
  - name: Set up Flutter
    uses: subosito/flutter-action@v2
    with:
      channel: stable
      cache: true
      pub-cache-key: "any-custom-key"
```
