### ISSUE TITLE
Arm64 runners support

### ISSUE THREAD

**Issue by ferraridamiano** [subosito/flutter-action#345]
Github just [released arm64](https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/) actions for linux. I tried to setup flutter with `flutter-action` on `ubuntu-24.04-arm` but it failed. Will you add support also for arm runners?

**Comment by Npepperlinux** [comment]
> The official does not provide linux arm64 build, you can use snap instead

The official [support deployment on linux-arm64](https://docs.flutter.dev/reference/supported-platforms#:~:text=Ubuntu%20(Linux)-,x64%2C%20Arm64,-20.04%20LTS%20to) and provide dart-sdk-linux-arm64([3.24.5 SDK example](https://storage.googleapis.com/flutter_infra_release/flutter/a18df97ca57a249df5d8d68cd0820600223ce262/dart-sdk-linux-arm64.zip)). It should be possible if you don't reference [release_linux.json](https://storage.googleapis.com/flutter_infra_release/releases/releases_linux.json).

**Comment by SecondFlight** [comment]
Here's an alternative way to install Flutter for Linux that works on ARM. I've tested this on `ubuntu-24.04-arm` and it's working as expected.

```yaml
jobs:
  build-linux:
    # If you want to run the same action on x86 and ARM, you can use a matrix strategy
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies from Apt
        run: |
          sudo apt-get update -y && sudo apt-get upgrade -y;

          # These packages are listed in the setup instructions for Linux desktop. They may not all be necessary.
          # For reference: https://docs.flutter.dev/get-started/install/linux/desktop
          sudo apt-get install -y curl git unzip xz-utils zip libglu1-mesa clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev

      - name: Clone Flutter
        run: |
          # Shallow-clone Flutter to reduce download size
          git clone --depth 1 --branch 3.27.3 https://github.com/flutter/flutter.git $RUNNER_TEMP/flutter

          # Add Flutter to PATH
          echo "$RUNNER_TEMP/flutter/bin" >> $GITHUB_PATH

      - name: Install Flutter
        # Running "flutter doctor" will download Flutter's dependencies
        run: flutter doctor
      
      # More steps here...
```

If you want to use the same clone strategy on Windows, the code is similar:

```yaml
jobs:
  build-windows:
    runs-on: [windows-latest]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Clone Flutter
        run: |
          # Shallow-clone Flutter to reduce download size
          git clone --depth 1 --branch 3.27.3 https://github.com/flutter/flutter.git $env:RUNNER_TEMP\flutter

          # Add Flutter to PATH
          Add-Content $env:GITHUB_PATH "$env:RUNNER_TEMP\flutter\bin"
      
      - name: Install Flutter
        # Running "flutter doctor" will download Flutter's dependencies
        run: flutter doctor

      # More steps here...
```

**Comment by pugaizai** [comment]
you don't need to manually git clone, u just
```
steps:
  - name: Clone repository
    uses: actions/checkout@v4
  - name: Set up Flutter
    uses: subosito/flutter-action@v2
    with:
      channel: master
      flutter-version: 3.24.0
  - run: flutter --version
```
then linux arm works

**Comment by ferraridamiano** [comment]
Thanks for your solution @pugaizai. It works!

The issue with this action occurs when it's configured to use a flutter channel other than master.

**Comment by MiniSuperDev** [comment]
HI, how can I make it work with the latest version on stable?
It only works when you set the `flutter-version`, but I need to use latest to avoid update the ci.
In my case is with Apple M4 chip

**Comment by akshaybabloo** [comment]
> you don't need to manually git clone, u just
> 
> ```
> steps:
>   - name: Clone repository
>     uses: actions/checkout@v4
>   - name: Set up Flutter
>     uses: subosito/flutter-action@v2
>     with:
>       channel: master
>       flutter-version: 3.24.0
>   - run: flutter --version
> ```
> 
> then linux arm works

With this I am getting an error as:

```
The following required packages were not found:
   - gtk+-3.0
```

After installing all the libs then this works.

Here is the runner log - https://github.com/akshaybabloo/flutter_arm_test/actions/runs/14263080900/job/39978830950

**Comment by hurelhuyag** [comment]
Flutter has ARM64 sdk. But it is packaged as a snap. Can we use it to build arm64 app? But it seems only latest versions available

API is: `curl -H 'Snap-Device-Series: 16' http://api.snapcraft.io/v2/snaps/info/flutter`

**Comment by hurelhuyag** [comment]
Latest version with stable chanel not working:

Runner log: https://github.com/hurelhuyag/flutter-arm64-action-demo/actions/runs/14819702105/job/41604983691

**Comment by kadenchoi-halo** [comment]
@ferraridamiano is correct
it will not work if channel is set to other than master

very inconvenient, I need to create another x64 instance for flutter build

**Comment by pugaizai** [comment]
> HI, how can I make it work with the latest version on stable?
> It only works when you set the `flutter-version`, but I need to use latest to avoid update the ci.
> In my case is with Apple M4 chip 

@MiniSuperDev i think you can try to set `flutter-version: stable`

**Comment by kcdev001** [comment]
Windows ARM64:

Config:
```
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: main
          flutter-version: 3.38.4
          cache: true
```

Error:
```
Checking Dart SDK version... 
Downloading Dart SDK from Flutter engine ... 
The current channel's Dart SDK does not support Windows Arm64, falling back to Windows x64...
Expanding downloaded archive with 7z...
```
