### ISSUE TITLE
Caching fails on MacOS runners

### ISSUE THREAD

**Issue by Mr-Pepe** [subosito/flutter-action#350]
Use the following action on `macos-latest`:

```
- name: Install Flutter
  uses: subosito/flutter-action@v2
  with:
    channel: "stable"
    flutter-version-file: pubspec.yaml
    cache: true
```

Get the following error:

```
Cache not found for input keys: flutter-macos-stable-3.27.1-arm64-17025dd88227cd9532c33fa78f5250d548d87e9a, flutter-macos-stable-3.27.1-arm64-17025dd88227cd9532c33fa78f5250d548d87e9a
Error: The template is not valid. subosito/flutter-action/v2/action.yaml (Line: 108, Col: 14): hashFiles('**/pubspec.lock') failed. Fail to hash files under directory '/Users/runner/work/xxx',subosito/flutter-action/v2/action.yaml (Line: 109, Col: 23): hashFiles('**/pubspec.lock') failed. Fail to hash files under directory '/Users/runner/work/xxx'
```

There is [a workaround](https://github.com/actions/runner/issues/449#issuecomment-1926649741) in the [related issue](https://github.com/actions/runner/issues/449) by explicitly providing the file to hash instead of using wildcards. 

There seems to be little progress on the issue. Would it be possible to allow specifying the paths to `pubspec.lock` files explictily?
