### ISSUE TITLE
Actions taking too long due to android sdk dependencies.

### ISSUE THREAD

**Issue by crafael23** [subosito/flutter-action#351]
```yaml
  test-build:
    needs: [create-pr, check-conflicts]
    if: needs.check-conflicts.outputs.mergeable == 'true'
    runs-on: macos-15
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Java JDK
        uses: actions/setup-java@v4.7.0
        with:
          distribution: "oracle"
          java-version: "17"
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: 3.27.0
          cache: true

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: latest

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
      - name: install dependencies
        run: |
          flutter pub get
          pnpm install
          dart run build_runner build --delete-conflicting-outputs
          pnpm prisma generate
          pnpm prisma migrate dev --name dev
      - name: Update pubspec.yaml with latest migration directory
        run: ./update_pubspec.sh

      - name: Build
        id: build_apk
        run: flutter build apk
```

Not out of the ordinary, just some scripts running, the problem is the actual flutter build apk command

It takes a HUGE ammount of time to finish(vs my computer where it finishes in 20 seconds)

![Image](https://github.com/user-attachments/assets/d988bd56-f975-4d65-a682-9e86d33050d5)

It seems that its due to the NDK  Android SDK build tools and Cmake not being available. 

Im unsure of what to do to fix this, any insights?

**Comment by kuhnroyal** [comment]
Use this action: https://github.com/android-actions/setup-android

**Comment by crafael23** [comment]
Using setup android took the assebleRelease task from ~230s to 193

![Image](https://github.com/user-attachments/assets/87508615-f21f-46dd-80ad-5a94b5fc7681)

Still quite a bit of time.

(im quite new to this) what else should I cache to make sure its improved futher?

But the setting up the android sdk tools action takes quite a bit too. Around 30-35 seconds and it doesnt have a chaching option which makes the time saved on the build task basically rendring it moot.

Also I notice that every time flutter build apk (options) is run the dependencies are also fetched again(perhaps from cache) but the reason why it takes so long is that there is something else not cached missing preventing it to run the Graddle assembleRelease task.

Any ideas?

**Comment by kuhnroyal** [comment]
You can enable gradle cache for the setup-java action: https://github.com/actions/setup-java#caching-gradle-dependencies
I would suggest to run the APK build with the verbose flag and see what takes time.

There are many other factors involved, which runner? size? self-hosted?

**Comment by crafael23** [comment]
Standard MacOS latest Runner. I'll try a couple of things and I'll come back.

**Comment by crafael23** [comment]
I got it now.

There is some misconfiguration still happening in my flutter app as it attempts to use previous versions of  build tools cmake and ndk, causing it to have to download them.

Also caching gradle dependencies as you mentioned also helped a lot.

I basically had to update my project (reinitializing flutter) to the newest version available.

Changed the runner to ubuntu-latest and cut times dramatically, now i only have to setup java and setup the cache for gradle and that solves it.

Heres an example.

```yaml
name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"
          cache-dependency-path: |
            android/gradle/wrapper/gradle-wrapper.properties
            android/build.gradle.kts
            android/app/build.gradle.kts

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.29.2"
          cache: true

      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk --verbose
```
