### ISSUE TITLE
Action fails with flutter v3.29.3

### ISSUE THREAD

**Issue by MSOB7YY** [subosito/flutter-action#355]
error output
![Image](https://github.com/user-attachments/assets/00890a63-7cb2-4b31-a44b-990cb607263d)

workflow.yml
![Image](https://github.com/user-attachments/assets/e3585c19-9bef-4224-be82-91625b6f571e)

pubspec.yaml
![Image](https://github.com/user-attachments/assets/f74c318d-57cf-47b9-8119-f177e7ccbf1f)

what could be the issue? i heard that v2 should manually be pointed to the latest flutter version?

**Comment by SrS2225a** [comment]
Here is my workflow code to setup flutter which works fine:

```yaml
  build_android:
    name: Build Flutter App (Android)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Build App Bundle
        run: flutter build appbundle --release
```

For the environment in `pubspec.yaml`, I have it as this:
```yaml
environment:
  sdk: '>=3.5.0 <4.0.1'
  flutter: '3.29.3'
```

Also, I am not sure why you are calling for dart, as flutter SDK already comes with dart built in
