### ISSUE TITLE
Mixing specific versions and channels is kinda unergonomic

### ISSUE THREAD

**Issue by benthillerkus** [subosito/flutter-action#357]
I often want to write strategies like so
```yaml
strategy:
  matrix:
    flutter: [3.29.3, 3.32.0, dev, master]
````

But because of the segmentation of the version into `channel` and `flutter-version` I cannot easily just write

```yaml
- uses: subosito/flutter-action@v2
  with:
    flutter-version: ${{ matrix.flutter }}
```

Currently I'm doing

```yaml
- uses: subosito/flutter-action@v2
  if: ${{ matrix.flutter }} != 'dev' && ${{ matrix.flutter }} != 'master'
  with:
    flutter-version: ${{ matrix.flutter }}
    cache: true

- uses: subosito/flutter-action@v2
  if: ${{ matrix.flutter }} == 'dev' || ${{ matrix.flutter }} == 'master'
  with:
    channel: ${{ matrix.flutter }}
    cache: false
```

But I'd rather not have to
