### ISSUE TITLE
How to use the master channel?

### ISSUE THREAD

**Issue by qimingweng** [subosito/flutter-action#37]
The beta and dev channels seem to work, but what about master?

**Comment by subosito** [comment]
Hi @qimingweng, currently we do not support master channel directly, but you can use it by:

```yaml
- uses: subosito/flutter-action@v1
  with:
    channel: 'dev'
- run: flutter channel master
- run: flutter upgrade
```
