### ISSUE TITLE
Error when using channels

### ISSUE THREAD

**Issue by Neamar** [subosito/flutter-action#39]
Hello!

Since the last Flutter update three days ago, the channel feature seems broken :(

Here is an excerpt:

```yml
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta' # flutter web is not stable yet
      - run: flutter --version
```

Before the Flutter update three days ago:
```
Run flutter --version
Flutter 1.17.0-3.4.pre • channel beta • https://github.com/flutter/flutter.git
```

Now:
```
Run flutter --version
Flutter 1.17.0 • channel stable • https://github.com/flutter/flutter.git
```

I assume the path to download Flutter archive changed?

Thanks for the GithubAction, it's really neat!

(example live URL: https://github.com/Neamar/turn_me_on/runs/656069282?check_suite_focus=true)
