### ISSUE TITLE
Push the apk to release

### ISSUE THREAD

**Issue by asjqkkkk** [subosito/flutter-action#4]
Hello,I want to know how to put the apk file generated by the github-action into the release of my github project.😊😊

**Comment by subosito** [comment]
You can use another action for that purpose, like, https://github.com/marketplace/actions/github-action-publish-binaries. So, you can:

```yaml
steps:
- uses: actions/checkout@v1
- uses: actions/setup-java@v1
  with:
    java-version: '12.x'
- uses: subosito/flutter-action@v1
  with:
    flutter-version: '1.7.8+hotfix.4'
- run: flutter pub get
- run: flutter test
- run: flutter build apk
- uses: skx/github-action-publish-binaries@master
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  with:
    args: 'build/app/outputs/apk/release/app-release.apk'
```

**Comment by asjqkkkk** [comment]
@subosito 
Thank you!
But after I changed my <code>yml</code> file to:
```
name: Flutter CI

on:
  push:
    branches:
      - dev
      - master
      - action_test

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
#        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.7.8+hotfix.4'
          channel: 'stable'
      - run: flutter packages get
      - run: flutter test
      - run: flutter build apk --target-platform android-arm --split-per-abi
      - run: ls
      - run: mv build/app/outputs/apk/release/app-armeabi-v7a-release.apk build/app-armeabi-v7a-release.apk
      - uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
        with:
          args: 'build/app-armeabi-v7a-release.apk'

#      - run: curl
```

The github-action logs:

![image](https://user-images.githubusercontent.com/30992818/64306589-e3457e00-cfc5-11e9-98c3-d00dd6791908.png)

![image](https://user-images.githubusercontent.com/30992818/64306603-f5bfb780-cfc5-11e9-9bbc-9daa0883b088.png)

Could you give me some help?😊😊

**Comment by asjqkkkk** [comment]
![image](https://user-images.githubusercontent.com/30992818/64306808-90b89180-cfc6-11e9-958a-a65e3fdda3aa.png)
And I have set the token

**Comment by mirkancal** [comment]
Mine return succesful and provide me a apk link.

https://uploads.github.com/repos/mirkancal/{repo_name}/releases/null/assets?name=app-release.apk

However I can't see it on releases tab, also I can't view it via link.
Link returns this json.

{"message":"Bad Content-Length: ","request_id":"{id of the request}"}

My project is in the private repo, is it related?

.yml I had is:

```
name: Flutter Release Apk

on: [push, pull_request]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
      - uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'build/app/outputs/apk/release/app-release.apk'
```

**Comment by nabilnalakath** [comment]
I was able to push the APK to release using a different github action. You can read about it here - https://link.medium.com/1q1D4Fgbv0

**Comment by tianhaoz95** [comment]
Hi @nabilnalakath, my workflow pushes to actions storage find, you can take a look at this workflow file:

```yml
deploy-android:
    name: Deploy Android app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.9.1+hotfix.4'
          channel: 'stable'
      - run: cd ./iwfpapp && flutter build apk  --release
      - name: upload artifects
        uses: actions/upload-artifact@master
        with:
          name: android-app
          path: iwfpapp/build/app/outputs
```
