### ISSUE TITLE
Error with Android licences for Android R

### ISSUE THREAD

**Issue by chimanos** [subosito/flutter-action#41]
Hello,

After upgrading flutter to the latest version (1.17.0) my build for Android on Github Actions don't works anymore. 

I have this following error: 

**_Could not determine the dependencies of task ':app_settings:compileReleaseKotlin'.
Failed to install the following SDK components: platforms;android-R Android SDK Platform R
The SDK directory is not writable (/usr/local/lib/android/sdk)_**

Here is a flutter doctor on the runner:

**_Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.1, on Linux, locale C.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[!] Android Studio (not installed)
[!] Connected device
    ! No devices available_**

Do you have any ideas ? 

Thank you

**Comment by dshukertjr** [comment]
Hi,

I am experiencing very similar issue. This is the error message I am getting

```
Could not determine the dependencies of task ':app_settings:compileReleaseAidl'.

> Failed to install the following SDK components:

      platforms;android-R Android SDK Platform R

  The SDK directory is not writable (/usr/local/lib/android/sdk)
```

Here is my yaml file
```
name: Distribute test apps

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.12.13+hotfix.8"

      - name: build android apk
        run: |
          flutter pub get
          flutter test
          # flutter build apk --flavor dev  --target-platform android-arm,android-arm64
          flutter build apk

```
