### ISSUE TITLE
Allow usage of specific Flutter version without specifying channel

### ISSUE THREAD

**Issue by kpsroka** [subosito/flutter-action#43]
Hi!

I've stumbled across an issue recently, where the flutter-action would fail because of version/channel mismatch. This was triggered by Flutter's `1.17.1` going from beta to stable channel. My config was:

```
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.17.1"
          channel: beta
``` 

Now, since the 1.17.1 changed channel to stable, my config became invalid - there's no longer a '1.17.1' version with 'beta' channel in https://storage.googleapis.com/flutter_infra/releases/releases_linux.json.

Unfortunately, right now there's no way to avoid breakages in case an SDK version gets moved across channels - without specifying one, the 'stable' one is going to be used.

My proposal is to introduce a match-all channel value (let's say `channel: any`) that will ignore checking the channel match in the .json files.
