### ISSUE TITLE
weird behavior when running in ubuntu-latest

### ISSUE THREAD

**Issue by elmissouri16** [subosito/flutter-action#45]
the action works fine when I use Windows or Mac and give me error in build when I use ubuntu-latest or any other version 

here is my setup

```
name: Build and release

on: push

jobs:
  my-job:
    name: Build App
    runs-on: windows-latest
    
    if: contains(github.event.head_commit.message, 'RLS')
    steps:
    - uses: avkviring/telegram-github-action@v0.0.7
      env:
        telegram_to: ${{ secrets.TELEGRAM_TO }}  
        telegram_token: ${{ secrets.TELEGRAM_TOKEN }}
        event: ${{ toJson(github.event) }}
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.17.2'
    - run: dart --version  
    - run: flutter pub get
    - run: flutter build apk --release 
    - name: Push APK to Releases
      uses: ncipollo/release-action@v1
      
      with:
        artifacts: "build/app/outputs/apk/release/*.apk"
        token: ${{ secrets.TOKEN }}
        tag: v3
```
