### ISSUE TITLE
Link to pubspec.yaml instead of specifying version

### ISSUE THREAD

**Issue by friebetill** [subosito/flutter-action#47]
Currently, when a new flutter version is released and one wants to update their project, one must always change the version in `pubspec.yaml` and the version in the github action. 

This is not terribly, but a little annoyance because one has to keep it in mind when changing the version.

I came up with three ideas to solve this:
1. In the yaml github action file link to the version in pubspec.yaml
2. Add a script to the github action file that substitutes the version  when the github action is executed
3. Ask if the feature can be added.

The first version is not possible, as far as I understand it, because in yaml [one can' t reference to a line in another file](https://stackoverflow.com/questions/22639727/yaml-reference-another-variable-in-another-file).

The second solution is probably not possible either, because one would have to replace the github action file while it is running. Did not test this.

I can't think of any other solution at the moment, so I'm asking if you consider this a problem and want to implement it.

**Comment by daohoangson** [comment]
I'm currently doing this in my workflow:

```yaml
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Flutter version from pubspec
        run: |
          set -e

          brew install yq
          _flutterVersion=$( yq read pubspec.yaml environment.flutter )
          echo "::set-env name=FLUTTER_VERSION::${_flutterVersion}"
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
```

**Comment by beroso** [comment]
Thank you @daohoangson, your example is very useful.

I just want to add a hint: the `set-env` command was recently deprecated [(see here)](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/), so I adapted it in my workflow: 

```yaml
echo "FLUTTER_VERSION=${_flutterVersion}" >> $GITHUB_ENV
```

**Comment by zgosalvez** [comment]
Much appreciated @daohoangson! I use this a lot and tend to make mistakes, even when copying and pasting. I wrapped this as a GitHub Action for ease of use. I hope y'all find this helpful. 🤗 https://github.com/marketplace/actions/get-the-flutter-version-environment

**Comment by subosito** [comment]
I am planning to support this, and having something like:

```yaml
- uses: subosito/flutter-action@v1
  with:
    flutter-version: 'pubspec'
    channel: 'stable' # we can omit this
```

What do you guys think? Is that OK?
