### ISSUE TITLE
install ninja to setup environment?

### ISSUE THREAD

**Issue by liudonghua123** [subosito/flutter-action#49]
I used this github action a lot, but recently when I build linux packages, it always failed with `CMake Error: CMake was unable to find a build program corresponding to "Ninja". CMAKE_MAKE_PROGRAM is not set.`, see https://github.com/flutter/flutter/issues/59750 for more details.
It seems lack of ninja, could you install `ninja` by default in order for building linux packages.

**Comment by liudonghua123** [comment]
Finally, I can add a step like the following to make it work for linux package.

```yarml

      - name: Patch for linux build
        run: |
          flutter doctor
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
          flutter doctor

```

**Comment by Merrit** [comment]
I also had to add libblkid-dev before it would work, which looked like this:

```
  - run: sudo apt-get update -y
  - run: sudo apt-get install -y ninja-build libgtk-3-dev libblkid-dev
```

Here is my entire workflow.yml for reference:

```
name: Check Linux build succeeds on PR
'on': pull_request
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update -y
      - run: sudo apt-get install -y ninja-build libgtk-3-dev libblkid-dev
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: dev
      - run: flutter config --enable-linux-desktop
      - run: flutter pub get
      - run: flutter build linux

```
