### ISSUE TITLE
The process '/bin/tar' failed with exit code 2

### ISSUE THREAD

**Issue by humazed** [subosito/flutter-action#5]
![image](https://user-images.githubusercontent.com/8838182/64487372-ee084900-d239-11e9-970f-b2301c2b7bea.png)

and my action:

```yaml
name: Flutter action

on:
  push:
    branches:
    - master
    - release/*

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

#     steps:
#       - uses: actions/checkout@v1
#       - uses: actions/checkout@v1
#       - uses: actions/setup-java@v1
#         with:
#           java-version: '12.x'
#       - uses: subosito/flutter-action@v1
#         with:
#           flutter-version: '1.7.8+hotfix.4'
#       - run: flutter pub get
#       - run: flutter test
#       - run: flutter build apk
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.7.8+hotfix.4'
          channel: 'stable'
      - run: flutter packages get
      - run: flutter test
      - run: flutter build apk

```
