### ISSUE TITLE
Flutter master channel

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [subosito/flutter-action#51]
It would be benificial if there was an option for the `master` channel as well.

**Comment by softmarshmallow** [comment]
Any updates? @subosito

**Comment by etx** [comment]
I just tried running `flutter channel master && flutter upgrade` and that works as expected for a quick fix.

**Comment by subosito** [comment]
Hi, I've added experimental support for master channel. You can try using:

```yaml
      - uses: subosito/flutter-action@master
        with:
          channel: master
```

You can check the example of workflow pipeline in https://github.com/subosito/flutter-action-example/runs/1224108745?check_suite_focus=true.
