### ISSUE TITLE
publish `example` does not work. (building flutter app in other directory than root)

### ISSUE THREAD

**Issue by softmarshmallow** [subosito/flutter-action#55]
general project structure, as you can see here [flutter_timeline](https://github.com/softmarshmallow/flutter-timeline)

my config looks like this
```yml
name: Flutter Web
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: cd example
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release
      - run: |
          cd build/web
          git init
          git config --global user.email woojoo@softmarshmallow.com
          git config --global user.name softmarshmallow
          git status
          git remote add origin https://${{secrets.commit_secret}}@github.com/softmarshmallow/flutter-timeline.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f
```

ERROR
> Target file "lib/main.dart" not found.

```
 Run flutter build web --release8s
    FLUTTER_HOME: /opt/hostedtoolcache/flutter/1.22.0-1.0.pre-dev/x64
Run flutter build web --release
  flutter build web --release
  shell: /bin/bash -e {0}
  env:
    my_secret: ***
    FLUTTER_HOME: /opt/hostedtoolcache/flutter/1.22.0-1.0.pre-dev/x64
Downloading Web SDK...                                              1.1s
Target file "lib/main.dart" not found.
##[error]Process completed with exit code 1.
```

why wont it find directory? does it explicitly runs on root? not the pwd?
