### ISSUE TITLE
Cannot Run subosito/flutter-action@v1

### ISSUE THREAD

**Issue by msyagami** [subosito/flutter-action#56]
CI doesn't run due to flutter-action error. 
![image](https://user-images.githubusercontent.com/53424270/93190648-772d4800-f6f8-11ea-9855-487f431fd3d5.png)

Error: 

```
Run subosito/flutter-action@v1
  with:
    flutter-version: 1.22.0-12.0.pre
    channel: dev
  env:
    JAVA_HOME_12.0.2_x64: /__t/jdk/12.0.2/x64
    JAVA_HOME: /__t/jdk/12.0.2/x64
    JAVA_HOME_12_0_2_X64: /__t/jdk/12.0.2/x64
/usr/bin/docker exec  eac03e88df5b8c5709cc0f93a33a43d78b820486713911f8ea0c28053d9066be sh -c "cat /etc/*release | grep ^ID"
/usr/bin/tar x --warning=no-unknown-keyword -C /__w/_temp/temp_253760480 -f /__w/_temp/19d84305-8dca-453d-9633-2ee35b7d4a4d
tar (child): xz: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
/usr/bin/tar: Child returned status 2
/usr/bin/tar: Error is not recoverable: exiting now
##[error]The process '/usr/bin/tar' failed with exit code 2
```

Code:

```
name: Flutter Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: google/dart:latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.22.0-12.0.pre'
        channel: 'dev'
    - run: flutter channel master 
    - run: flutter upgrade
    - run: flutter doctor -v
    - run: flutter config --enable-web
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk
    - run: flutter build web
```
