### ISSUE TITLE
xz: Cannot exec: No such file or directory

### ISSUE THREAD

**Issue by KlausJokinen** [subosito/flutter-action#65]
I've started getting this error when using Flutter Actions.

Output:
```
[CI/build] ⭐  Run subosito/flutter-action@v1.4.0
[CI/build]   ☁  git clone 'https://github.com/subosito/flutter-action' # ref=v1.4.0
[CI/build]   🐳  docker cp src=act/subosito-flutter-action@v1.4.0 dst=/actions/
[CI/build]   💬  ::debug::latest version from channel stable is 1.22.2
[CI/build]   💬  ::debug::isExplicit: 1.22.2-stable
[CI/build]   💬  ::debug::explicit? true
[CI/build]   💬  ::debug::checking cache: /opt/hostedtoolcache/flutter/1.22.2-stable/x64
[CI/build]   💬  ::debug::not found
[CI/build]   💬  ::debug::Downloading Flutter from Google storage https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_1.22.2-stable.tar.xz
[CI/build]   💬  ::debug::Downloading https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_1.22.2-stable.tar.xz
[CI/build]   💬  ::debug::Destination /tmp/409f74e3-7821-45c1-a427-d7132a4b0b84
[CI/build]   💬  ::debug::download complete
[CI/build]   💬  ::debug::Checking tar --version
[CI/build]   💬  ::debug::tar (GNU tar) 1.30%0ACopyright (C) 2017 Free Software Foundation, Inc.%0ALicense GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.%0AThis is free software: you are free to change and redistribute it.%0AThere is NO WARRANTY, to the extent permitted by law.%0A%0AWritten by John Gilmore and Jay Fenlason.
| [command]/bin/tar x --warning=no-unknown-keyword -C /tmp/temp_748860406 -f /tmp/409f74e3-7821-45c1-a427-d7132a4b0b84
| tar (child): xz: Cannot exec: No such file or directory
| tar (child): Error is not recoverable: exiting now
| /bin/tar: Child returned status 2
| /bin/tar: Error is not recoverable: exiting now
[CI/build]   ❗  ::error::The process '/bin/tar' failed with exit code 2
[CI/build]   ❌  Failure - subosito/flutter-action@v1.4.0
Error: exit with `FAILURE`: 1
```

main.yml:
```
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - '**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Delete
        uses: ame-yu/action-delete-latest-release@v2
        with:
          github_token: ${{ secrets.PROJECT_TOKEN}}
      - uses: benjlevesque/short-sha@v1.1
        id: short-sha
        with:
          length: 10
      - run: echo $SHA
        env: 
          SHA: ${{ steps.short-sha.outputs.sha }}
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: 'stable' # or: 'dev' or 'beta'
      - run: flutter pub get
      - run: flutter build apk --split-per-abi
      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk"
          tag: ${{ env.SHA }}
          token: ${{ secrets.PROJECT_TOKEN }}
```

Thanks 👍
