### ISSUE TITLE
Support beta versions of flutter (null-safety)

### ISSUE THREAD

**Issue by HarvsG** [subosito/flutter-action#69]
I am using the beta version of flutter, so I can develop using the upcoming null-safety feature. how do I specify the flutter version in the .yml file?
```yml
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
          flutter-version: "1.24.0-10.2.pre"
```
causes an error.

https://flutter.dev/docs/development/tools/sdk/releases

**Comment by HarvsG** [comment]
To answer my own question
```yml      
- uses: subosito/flutter-action@v1
        with:
          channel: "beta"
          flutter-version: "1.24.0-10.2.pre"
```
