### ISSUE TITLE
uses: subosito/flutter-action@v1 fails when used on a self-hosted runner running inside Docker

### ISSUE THREAD

**Issue by nicolabba** [subosito/flutter-action#72]
We are running our self-hosted runner as a Docker image, when running the action with this yml:

```
name: Flutter CI

# This workflow is triggered on pushes to the repository.

on:
  push:
    branches:
      - master

jobs:
  build:
    # This job will run on ubuntu virtual machine
    runs-on: self-hosted
    steps:

      # Setup Java environment in order to build the Android app.
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      # Setup the flutter environment.
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      # Get flutter dependencies.
      - run: flutter pub get

      # Check for any formatting issues in the code.
      - run: flutter format --set-exit-if-changed .

      # Statically analyze the Dart code for any errors.
      - run: flutter analyze .

      # Run widget tests for our flutter project.
      - run: flutter test

      # Build apk.
      - run: flutter build apk

      # Upload generated apk to the artifacts.
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
```
This is the error:
![image](https://user-images.githubusercontent.com/29799630/103463889-fdb17800-4d2f-11eb-80a5-f2be15195340.png)

I have seen this happen in a number of closed issues where the solution was to remove the lines:
```
    container: 
      image: google/dart:latest
```
But in our case that is not really possible.
Is there anything we can do to make it work?
