### ISSUE TITLE
Error: unable to find release for 1.22.4

### ISSUE THREAD

**Issue by coroutineDispatcher** [subosito/flutter-action#73]
I am new to automation so I do no exclude the possibility that I might be doing something wrong as well. I am facing this issue.

The setup that I have is:

```
name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  flutter_linter:
    name: Flutter action
    runs-on: macos-latest
    steps:
      - uses: subosito/flutter-action@v1.4.0
        with:
          flutter-version: '1.22.4'
          channel: 'main'
      - run: flutter pub get
      - run: flutter analyze
```

Latest version
<img width="691" alt="Screenshot 2021-01-10 at 13 19 32" src="https://user-images.githubusercontent.com/31472273/104122633-7de66780-5346-11eb-80f5-dc3f2f5e3100.png">

One version before:
<img width="499" alt="Screenshot 2021-01-10 at 13 17 45" src="https://user-images.githubusercontent.com/31472273/104122590-3bbd2600-5346-11eb-9f14-61e56aed22c5.png">

Also, same if I use:

```
jobs:
  flutter_linter:
    name: Flutter action
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1.4.0
        with:
          flutter-version: '1.22.4'
          channel: 'main'
      - run: flutter pub get
      - run: flutter analyze
```
<img width="758" alt="Screenshot 2021-01-10 at 13 37 35" src="https://user-images.githubusercontent.com/31472273/104123040-0108bd00-5349-11eb-8da5-a2e5094935b6.png">
