### ISSUE TITLE
flutter 1.22.6

### ISSUE THREAD

**Issue by abiudorina** [subosito/flutter-action#76]
Please add affordances for flutter 1.22.6

**Comment by foxted** [comment]
You can specify the version in the action: 

```yaml
steps:
  - name: Setup Flutter
     uses: subosito/flutter-action@v1
     with:
       flutter-version: '1.22.5'
```
