### ISSUE TITLE
Should add pub cache to PATH?

### ISSUE THREAD

**Issue by kentcb** [subosito/flutter-action#78]
_(whoops! Wrote this up last night but forgot to submit it)_

Hi,

Thanks for this useful action.

[The code](https://github.com/subosito/flutter-action/blob/5781588262c6ac190635673b08ecdc1245abc4d7/src/installer.ts#L49) currently adds `$FLUTTER_ROOT/bin` and `$FLUTTER_ROOT/bin/cache/dart-sdk/bin` to the `PATH`, but it doesn't add the pub cache. As a result, the following warning is output during pub activation (`flutter pub global activate foo`):

> Warning: Pub installs executables into /opt/hostedtoolcache/flutter/1.26.0-17.8.pre-beta/x64/.pub-cache/bin, which is not on your path.

In order to hack around this, I needed to add this step after installing Flutter:

```yaml
- name: Add pub cache to path
  shell: bash
  run: |
    PUB_CACHE=$FLUTTER_HOME/.pub-cache/bin
    echo "Adding '$PUB_CACHE' to PATH"
    echo "export PATH=$PATH:$PUB_CACHE" >> $GITHUB_PATH
```

To be honest, I have no idea why I need to use `FLUTTER_HOME` rather than `FLUTTER_ROOT` as exported [here](https://github.com/subosito/flutter-action/blob/5781588262c6ac190635673b08ecdc1245abc4d7/src/installer.ts#L48). Everything I've read suggests the call to `exportVariable` should allow me to consume it in subsequent steps, but it simply isn't available. Whilst it doesn't really matter, I'd love to understand why that is if you have any ideas.

Would it be possible for the action to add `$FLUTTER_ROOT/.pub-cache/bin` to the `PATH`?
