### ISSUE TITLE
The action init failed with http error

### ISSUE THREAD

**Issue by tianhaoz95** [subosito/flutter-action#8]
Hi, I was trying to use it for a flutter app I recently started, but the action init failed with the following message:

<img width="940" alt="failed_screenshot" src="https://user-images.githubusercontent.com/16887772/65843567-235b0080-e2e7-11e9-8404-41bcca266501.png">

Here is the action workflow I added:

```yml
name: PR checks

on: [push]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.8.4'
          channel: 'beta'
      - run: flutter pub get
      - run: flutter test
```

Do you know what might have happened and what might be a work around? I can probably post a fix if you can point me to where you think the problem is.
