### ISSUE TITLE
Flutter 2.0.1

### ISSUE THREAD

**Issue by xapatjb4** [subosito/flutter-action#81]
Hey I tried running this with
```
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.0.1'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk
    - run: flutter build ios --release --no-codesign
```

But it hung on subosito flutter action
![Screen Shot 2021-03-10 at 11 27 43 AM](https://user-images.githubusercontent.com/31086996/110662705-c0d08a00-8193-11eb-87da-e62298b314d1.png)

Would this have anything to do with using the newer flutter version?
