### ISSUE TITLE
`pub get` fail when dependencies with private git repo

### ISSUE THREAD

**Issue by kutear** [subosito/flutter-action#84]
```
  ***-libs:
    git: 
      url: git@github.com:**/**.git
      ref: master
      path: **
```
the repo is private, when run `flutter pub get`  return `git@github.com: Permission denied (publickey).`

**Comment by kutear** [comment]
I got. just use access token to request, just like https://user:token@github.com/**/**.git

**Comment by copsterr** [comment]
Would you mind sharing your GitHub action config? I'm facing the same problem. Here's my configuration. 
```yml
name: Release

on:
  release:
    types: [published]
    branches:
      - "main"

env:
  REGISTRY: ghcr.io
  GITHUB_TOKEN: ${{secrets.ACTION_TOKEN}}

jobs:
  release-image:
    timeout-minutes: 15
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Flutter action
        uses: subosito/flutter-action@v1.5.3
        with:
          channel: "stable"
      - name: Get Dependencies
        run: |
          git config --global url."https://my-org-name:${GITHUB_TOKEN}@github.com".insteadOf "https://github.com"
          flutter pub get 
```
