### ISSUE TITLE
flutter-action job fails when I use a private container

### ISSUE THREAD

**Issue by HRahimy** [subosito/flutter-action#96]
### Container registry setup

I use the following Dockerfile to create an image that I then push to google cloud container registry as a private image. I want to run my CD workflow in my workflow so that I can fetch deployment credentials that I store within my image.

> **Side Note:** Not sure if this is the safest method to be managing sensitive files such as `.jks` files I need to deploy my app to play store. I'd appreciate it if anyone could shed some light on this as well.

```Dockerfile
FROM ubuntu:latest

COPY Gemfile .
COPY Gemfile.lock .
COPY fastlane/ ./fastlane/
```

### Workflow configuration

Following is the contents of my workflow configuration in `.github/workflows/main.yml`. [See here for complete file](https://github.com/HRahimy/positive_affirmations/blob/mobile/user_signup_flow/.github/workflows/main.yml).

```yaml
# This is a basic workflow to help you get started with Actions

# [ ... ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: gcr.io/positive-affirmations-313800/droid-deploy-env:latest
      credentials:
        username: _json_key
        password: ${{ secrets.GCR_JSON_KEY }}

    steps:
      - uses: actions/checkout@v2
        working-directory: $HOME

      - uses: actions/setup-java@v1
        working-directory: $HOME
        with:
          java-version: '12.x'

      - uses: subosito/flutter-action@v1
        working-directory: $HOME
        with:
          flutter-version: '2.0.5'

      # [ ... ]

```

### Error occured :(

But I keep getting this error:

> Full logs available [here](https://github.com/HRahimy/positive_affirmations/runs/2647140619?check_suite_focus=true)

![image](https://user-images.githubusercontent.com/14905792/119239097-7a15ed80-bb4f-11eb-96b7-708387ae6707.png)
